### ISSUE TITLE
Feature request: count() variant that returns an array

### ISSUE THREAD

**Issue by yrp604** [Geal/nom#1007]
- Rust version : 1.37.0-nightly
- nom version : 5
- nom compilation features used: n/a

Hello!

Nom5 is wonderful, thank you for the hard work. When migrating my parser from 4 to 5, I could not find an analog to the `count_fixed!` macro. If I have missed this, or there is an idiomatic way to do this, please let me know. While arrays are not super useful at the moment, in theory const generics are landing sometime and should usher in a glorious new age of Vec free programming.

## Test case
Example test case:
```
extern crate nom;

use nom::number::complete::le_32;

fn two_ints(i: &[u8]) -> IResult<&[u8], [u32; 2]> {
    count_fixed(le_u32, 2)(i)
}

fn main() {
  let res = b"\x41\x41\x41\x41\x42\x42\x42\x42";
  assert_eq!(two_ints(res), Ok(b"", [0x41414141, 0x42424242]));
}
```

**Comment by Geal** [comment]
I removed `count_fixed` because that was the only use of `unsafe` in nom (not counting the dependencies, though) and it was quite hackish. A better implementation based on `MaybeUninit` would be good, but right now I'd prefer a parser that takes the result array as argument and writes into it. This would let the calling code decide where it is stored: passing a `&mut [u8]` could point either to an array or a `Vec`
