### ISSUE TITLE
Question: what does 01 mean within s_exp example?

### ISSUE THREAD

**Issue by omac777** [Geal/nom#1031]
Pardon my ignorance.  I read the wikipedia symbolic expression to further clarify what this example is all about.   What is that O1?  Thank you in advance.

https://github.com/Geal/nom/blob/master/examples/s_expression.rs#L150
```
fn s_exp<'a, O1, F>(inner: F) -> impl Fn(&'a str) -> IResult<&'a str, O1, VerboseError<&'a str>>
where
  F: Fn(&'a str) -> IResult<&'a str, O1, VerboseError<&'a str>>,
{
  delimited(
    char('('),
    preceded(multispace0, inner),
    context("closing paren", cut(preceded(multispace0, char(')')))),
  )
}
```

**Comment by MarkMcCaskey** [comment]
`O1` here is a generic, by looking at https://docs.rs/nom/5.0.1/nom/type.IResult.html we can see that it's the output type when used in the second place of `IResult`.  So this function takes a function `inner` which takes a string and returns an `IResult` which, if it's successful, returns some type `O1`.  Presumably `O1` stands for `Output1` in this case.

The `s_exp` function is a higher order function that takes a function and is returning a parsing function that parses something in the context of `(` + optional spaces before and optional spaces + `)` after. 

I probably just copied and pasted from somewhere else with multiple output types which is why it is that way -- I wrote this code pretty quickly.

**Comment by omac777** [comment]
Thank you for clarifying.
