### ISSUE TITLE
Help: writing a language parser

### ISSUE THREAD

**Issue by norman784** [Geal/nom#1040]
The documentation is not very clear to me about how to use certain combinators.

What I'm struggling to understand is how to i.e. parse this:

```
-- This will be an mvp program parsed and interpreted by Rust
-- get_current_time will return an incremental value, it will be provided by rust
-- println will map directly to rust println

process_input -> println 'process_input called'
render deltatime -> println 'render called with elapsed: {deltatime}'

game_loop last_time -> {
  current = get_current_time
  elapsed = current - last_time

  process_input
  render elapsed

  game_loop current
}

main -> {
  game_loop get_current_time 0
}
```

This is how my entry parser looks like

```rust
fn parse_expressions(i: &str) -> IResult<&str, Vec<Expression>> {
  many0(
    delimited(
      multispace0,
      alt((
        parse_function_delcaration,
        parse_comment,
      )),
      opt(multispace0)
    )
  )(i)
}
```
So the problem here for me is that it only parses only continuous comments or functions, so if I add a function then a comment and then another function the parser just stops, also the line breaks for some reason stops the parser, parsing comments are working, with this syntax I didn't manage to make a function parser to work, but with other I did, so I can parse when there is just one function, one or more comments, but not when they are mixed.

I used the examples as starting point, and also the combinators list (the documentation is, at least for me, not too good, the descriptions are short and not always descriptive for someone without experience with parsers).

Regards

**Comment by loewenheim** [comment]
`opt(multispace0)` immediately strikes me as odd, since the `multispace0` parser can't fail in the first place. But that shouldn't affect whether the parser works.

I can post some parsing code that I've used to parse a simple assembly language.
```rust
fn line(input: &str) -> ParseResult<Option<Instruction>> {
    terminated(
        delimited(space0, opt(instruction), space0),
        opt(line_comment),
    )(input)
}

fn program(input: &str) -> ParseResult<Vec<Instruction>> {
    map(separated_list(line_ending, line), |v| {
        v.into_iter().flatten().collect()
    })(input)
}
```

The first function parses a line, which possibly contains an instruction surrounded on both sides by zero or more spaces and possibly also a line comment. It returns `Option<Instruction>` because maybe the line was empty or it was only a comment.

The second function parses a list of lines delimited by line breaks, i.e., a program. Maybe `separated_list` is appropriate for your use case?

**Comment by norman784** [comment]
Sorry for the late reply, but thanks I will try that.
