### ISSUE TITLE
Tuple: type annotations required

### ISSUE THREAD

**Issue by trevor-scheer** [Geal/nom#1081]
## Prerequisites

- Rust version : `1.39.0`
- nom version : `5.0.1`
- nom compilation features used: `tuple`

## Explanation

First and foremost, thank you for taking the time to look at this. I appreciate the time and effort you've put into this project and helping others. I'm brand new to Rust, so please pardon my lack of knowledge here. Referencing both #990 and #991 since they seem to target the same or similar issue.

I'm having problems using the `tuple` combinator in even its simplest uses. The compiler seems to require some type annotations in order to use `tuple` - particularly around the 3rd type argument `E: ParseError`, however:

* I'm unsure why
* I'm unsure how to do that correctly
* This doesn't seem to be the case in the [docs example](https://docs.rs/nom/5.0.1/nom/sequence/fn.tuple.html) (and other examples I've come across).

@jamwaffles (sorry for the ping) - it seems you had a workaround [here](https://github.com/Geal/nom/issues/990#issuecomment-509598186) but I'm unsure how to correctly apply this workaround / solution to my case. Maybe something sticks out to you, if so I appreciate any insight you might have 🙇 

The compilation error:
```
error[E0283]: type annotations required: cannot resolve `_: nom::error::ParseError<&str>`
   --> src/main.rs:7:18
    |
7   |     let parser = tuple((alpha1, digit1, alpha1));
    |                  ^^^^^
    | 
   ::: /Users/trevorscheer/.cargo/registry/src/github.com-1ecc6299db9ec823/nom-5.0.1/src/sequence/mod.rs:288:30
    |
288 | pub fn tuple<I: Clone, O, E: ParseError<I>, List: Tuple<I,O,E>>(l: List)  -> impl Fn(I) -> IResult<I, O, E> {
    |                              ------------- required by this bound in `nom::sequence::tuple`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0283`.
error: could not compile `parser_playground`.
```

## Test case

The diff between working and non-working is surprising. As noted in the example below, uncommenting the assertion results in a successful compile. I suppose this means the compiler is able to infer the missing `Err` type based on the assertion https://github.com/Geal/nom/issues/990#issuecomment-523805234 but I don't imagine that I want to use assertions like this to inform the compiler.

For reference, this test case is borrowed from the docs example:
https://docs.rs/nom/5.0.1/nom/sequence/fn.tuple.html

Example test case:
```rust
use nom::character::complete::{alpha1, digit1};
use nom::error::ErrorKind;
use nom::sequence::tuple;
use nom::Err;

fn main() {
    let parser = tuple((alpha1, digit1, alpha1));

    // Uncomment these lines for a successful compilation
    // assert_eq!(
    //     parser("123def"),
    //     Err(Err::Error(("123def", ErrorKind::Alpha)))
    // );

    println!("{:?}", parser("abc123def"));
}
```

**Comment by jamwaffles** [comment]
> (sorry for the ping)

No problem! I should've given a better solution in the other thread.

`E: ParseError<I>` is a trait. My guess is `tuple` doesn't know which concrete type to use in this case. Both `digit` and `alpha1` don't give concrete types either (they also use `E: ParseError<I>`) so the output error type has to be explicitly defined.

In the `assert_eq!()` lines, the error is now defined on the right so Rust knows what concrete type to use. In this case, the inner error type is `(I, ErrorKind)` where `I` is `&str` in this case. If you leave that out, then the type must be specified manually like this:

```rust
use nom::character::complete::{alpha1, digit1};
use nom::error::ErrorKind;
use nom::sequence::tuple;
use nom::Err;

fn main() {
    let parser = tuple::<_, _, (_, ErrorKind), _>((alpha1, digit1, alpha1));

    println!("{:?}", parser("abc123def"));
}
```

I'm letting Rust infer the `I` in `(I, ErrorKind)` and the other type parameters with an underscore `_` because the only thing Rust actually needs to be told about is `ErrorKind` in the example above. Underscores maintain inference for the other type params.

Hope that helps!

I'm still getting to grips with the gnarlier bits of Rust's type system, so there might be a better way of doing the above. If so, someone please let me know 🙂

**Comment by trevor-scheer** [comment]
@jamwaffles super helpful! I appreciate the explanation of the `_` allowing inference, that brought it all together for me. Thanks for taking the time to write this up 😄

**Comment by jamwaffles** [comment]
I'm glad I could help!
