### ISSUE TITLE
Is it possible to make take_until with logical or?

### ISSUE THREAD

**Issue by armatusmiles** [Geal/nom#1099]
Hello, I can't find information about this question.

For example:
I want to parse a string that can finish with ";" or " "\r\n".
What is the best way to do that with nom?
I found take_until for that. But I can't find how to write properly something like that:
(pseudo code)
```
take_until(";" || "\r\n");
```

**Comment by armatusmiles** [comment]
I should use
```
alt((take_until(";"), take_until("\r\n")))(input)?;
```
closed

**Comment by inferiorhumanorgans** [comment]
From what I can tell this doesn't necessarily work as expected with nom 6.

Code:
`alt((take_until::<&[u8], &[u8], _>(&[0x00, 0x03]), take_until::<&[u8], &[u8], _>(&[0xFF, 0xFF])))(input)?`

Data:
`[0x01, 0x02, 0x03, 0xFF, 0xFF, 0x04, 0x05, 0x06, 0x00, 0x03]`

This will match up through 0x06 instead of up through 0x03.
