### ISSUE TITLE
`escaped` does not work with empty string

### ISSUE THREAD

**Issue by changhe3** [Geal/nom#1118]
It is pretty strange that `escape` doesn't work with empty string, that is [when the first character the function sees is a non-control-character that cannot be parsed by `normal` parser, it will return an error](https://github.com/Geal/nom/blob/41f461f0a19ce537dc17322e244bca3af695cc68/src/bytes/complete.rs#L489).

## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : rustc 1.41.0 (5e1a79984 2020-01-27) 
- nom version : 5.1.0
- nom compilation features used: default

## Test case

Please provide a short, complete (with crate import, etc) test case for
the issue, showing clearly the expected and obtained results.

Example test case:

```rust
#[macro_use]
extern crate nom;
use nom::character::complete::*;
use nom::bytes::complete::*;
use nom::IResult;

fn unquote<'a>(input: &'a str) -> IResult<&'a str, &'a str> {
    delimitedc(
        input,
        char('"'),
        escaped(none_of(r#"\""#), '\\', one_of(r#"\"rnt"#)),
        char('"'),
    )
}

fn main() {
    assert_eq!(r#""""#, Ok(("", "")));
}
```
The actual output is `Err(("\"", Escaped))` instead of `Ok("", "")`.

**Comment by Kampfkarren** [comment]
full-moon, a Lua parser with a good chunk written in nom, stumbled across this gotcha -- https://github.com/Kampfkarren/full-moon/pull/144

**Comment by Geal** [comment]
this fails because `none_of` must always produce something (its result is a `char`), so it should be `opt(none_of(r#"\""#))`  instead. Unfortunately, that would also fail in nom 6 because of #1336. That will be fixed in nom 7.

Also, the `delimitedc` function should not be used, it was there only for use by the macros (and tagged as `doc(hidden)`), and was removed along with the macros for nom 7

**Comment by Geal** [comment]
fix released in nom 7: https://crates.io/crates/nom/7.0.0
