### ISSUE TITLE
? in `chain!` not truly optional?

### ISSUE THREAD

**Issue by rekka** [Geal/nom#119]
Hi,

I might be misunderstanding the semantics of `?` in `chain!`, but it seems to differ from wrapping a parser in `opt!`:

```rust
named!(test1<()>, chain!(tag!("a")?,||{()}));
named!(test2<()>, chain!(opt!(tag!("a")),||{()}));
named!(test3<()>, map!(opt!(tag!("a")), |_| ()));
println!("{:?}", test1(b""));
println!("{:?}", test2(b""));
println!("{:?}", test3(b""));
```
prints
```
Incomplete(Size(1))
Done([], ())
Done([], ())
```
even though I'd expect all parsers be equivalent.

This is currently on caccedc86cbf6947a899b97d224240ad35f4eeb2.

**Comment by Geal** [comment]
Thanks for catching this. The bug is actually in `opt!`. An `Incomplete` is not a good enough reason to return `Done` in `opt!`, because if more data was coming, maybe `opt!` would consume it. So here, `chain!` has the expected behaviour.

If you know that the data you passed to `opt!` would never return `Incomplete` (example: you got the whole data in memory, or the format indicates how much data you needed), you can do something like this: `opt!(complete!(tag!("a")))`.

`complete!` will transform an `Incomplete` in an `Error`.
