### ISSUE TITLE
many0() False Fails with Streaming Functions

### ISSUE THREAD

**Issue by SeanMcLoughlin** [Geal/nom#1255]
I'm trying to move my parser that uses `complete` to `streaming` because I won't be able to load all of the data into memory. The test case below is a simplified recreation of the issue I'm experiencing, along with my expected output.

If my expected output isn't correct, could someone explain why, along with how I can get this simple case to work with a streaming function?

- Rust version : `rustc 1.48.0 (7eac88abb 2020-11-16)`
- nom version : 6.0.1
- nom compilation features used: `default`

## Test case
```rust
#[macro_use]
extern crate nom;

#[cfg(test)]
mod tests {
    use nom::IResult;
    use nom::multi::many0;
    // NOTE: Replacing this with the `complete` version of the method will pass.
    use nom::bytes::streaming::tag; 

    fn parse_apples(input: &str) -> IResult<&str, Vec<&str>> {
        many0(tag("apple"))(input)
    }

    #[test]
    fn match_apple_streaming() {
        assert_eq!(
            parse_apples("appleappleapple"),
            // Fails with: Err(Incomplete(Size(5)))
            Ok(("", vec!["apple", "apple", "apple"]))
        )
    }
}
```

**Comment by Lucretiel** [comment]
This is failing because, on the 4th loop, the parser attempts to run, and returns `Incomplete`. This is the correct behavior, because the parser *could* continue to parse successfully if more input was available, and it has no way of knowing that the end of "appleappleapple" is the *actual* end of the streaming input data.

In general, streaming parsers need to be looped outside of parser combinators. This is because nom parsers aren't capable of "saving" their state, so you need to take care of parsing each item (streaming more input if necessary) , processing it (in this case, pushing it to a vector), and then moving on to the next one. You yourself are the arbiter of when you're done, and need to take care of responding to an empty string either by returning success, or by streaming in more data, depending on the state of your data source.

**Comment by SeanMcLoughlin** [comment]
Thank you for your explanation. I'm going to close this since I think it's well known that documentation on how how to write a streaming parser is pretty lacking (see #1160), so this issue is just a duplicate at best.
