### ISSUE TITLE
error type names are confusing and hard to search and missing way to make them owned

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1356]
- `Err` enum is a terrible name very confusing
- `Err` is not in error module
- `ErrorConvert` is not in error module
- `IResult` is not in error module
- `Needed` is not in error module
- both `to_owned()` method now make no sense in v6 https://docs.rs/nom/6.2.1/nom/enum.Err.html#method.to_owned
- no `to_owned()` wait to convert a `Err<Error<&str>>` to `Err<Error<String>>`
- `convert()` from `Error` seem useless for user https://docs.rs/nom/6.2.1/nom/trait.ErrorConvert.html#tymethod.convert
- most utils method don't work with new V6 default error type.

And that just the few problem I hit doing a little parsing of bearer authorization http today. Keep it simple please, I already raise this problem several time in the past, it's worse in V6 ! Or I'm missing and so please enlighten me https://github.com/Geal/nom/blob/master/doc/error_management.md doesn't seem up to date.

We really need clear example of how to make error type owned, clear guide line on how nom parser should handle error properly. Maybe some idea here https://github.com/rust-lang/project-error-handling

**Comment by Geal** [comment]
Hello! First thing: please refrain from using strong language like "nightmare". This does not help in motivating me to work on it, especially considering I'm taking time from my much needed vacations to work in this release.

So:

> Err enum is a terrible name very confusing
do you have a suggestion for a different name? Note that it's unlikely to happen now as changing it will impact a lot of exsting parsers

> Err is not in error module
> ErrorConvert is not in error module
> IResult is not in error module
> Needed is not in error module
I'm not sure all of those would make sense in the error module. They are already available at the top level. The error module was more meant to hold custom error types.
> both to_owned() method now make no sense in v6 https://docs.rs/nom/6.2.1/nom/enum.Err.html#method.to_owned
what do you mean?
> no to_owned() wait to convert a Err<Error<&str>> to Err<Error<String>>
thre's on since 3944174
> convert() from Error seem useless for user https://docs.rs/nom/6.2.1/nom/trait.ErrorConvert.html#tymethod.convert
why does it seem useless? It's necessary to convert the input type with bits parsers, and if users have a custiom error type, they will need it. Maybe it needs more explanation in the docs?
> most utils method don't work with new V6 default error type.
you're right, most of those are removed in upcoming 7.0

The error management doc needs a rewrite, it's still mentioning macros that were removed recently.

Could you tell me what you were trying to achieve, that resulted in frustration with the API? Was it only about- converting the error type to an owned type? Would nom-supreme work for you, as @Lucretiel proposed?

**Comment by Stargateur** [comment]
I give up

**Comment by Geal** [comment]
@Stargateur Come on, I asked for more information in good faith, as I did for your comment last year: https://github.com/Geal/nom/issues/1132#issuecomment-683415688

If you don't explain your use cases, how can I better understand how to address them?

You need to understand two things here:
- changing public types, how they're imported, etc has a huge impact on existing code, and if I do it too often people do not migrate to the new version. The focus of version 7.0 is in fixing MSRV issues with dependencies, and removing old code, with very limited impact, so that upgrades are easy. Changing the name of a public type will go in the next major version
- I have very limited time to work on it due to family constraints, and as often in open source, it is unpaid work. The minimum you could do when opening an issue is to help me understand quickly how I can help you, and how it will benefit other users

**Comment by Stargateur** [comment]
Notice that for me all of this is kind of obvious, and I have tremendous difficulty to talk in English, I think I did make effort opening this, my purpose was "here what I find doing a little parser discovering V6" but you make my motivation go away with your strong word thing, I'm often use strong word, even if in my opinion nightmare in french is not that strong, at least at oral, do I need to add smiley to my sentence or do I need to take precaution at every sentence would make me even less likely to want to take 2 hours to write a message in English. Also, You didn't seem to be at all open to any change.

For the record I a big fan of nom overall, macro was very hard to use, but since V5 nom is incredible funny to use. But the big problem is Error handling, and it's frustrating for me to not understand why it's so complex in nom for in my eye nothing:

I don't understand your point about breaking change, my opinion about nom is that you are not afraid of breaking change and I love it. Sure, V5 to V6 is missing a guide but still I like see a crate change for better. You have probably the only crate in Rust that is used that much and going for a V7, THAT NICE. See https://0ver.org/. Of course I would not like a total breaking change, but renaming ? how easy is to just replace a identifier by another one ? Trust me the change in V5 => V6 was way harder to fix.

`Err` is a very bad name confusing with [`Err`](https://doc.rust-lang.org/std/result/enum.Result.html) from std **that is auto imported in scope**, I don't see how this name could be a good choice. Any name would be better and way more clear.

That talk about the variant of `Err`, "`Failure` => indicates an unrecoverable error" so why not `Unrecoverable` ? "`Error` means some parser did not succeed" `Failure` could more sense for this case, the problem of `Error` name is that `Err::Error` is non sense, an the error variant of error ?!?

An good name for `Err` could be `Outcome` or `Output`, etc. Every thing that is NOT already used by std.

You say, "They are already available at the top level. The error module was more meant to hold custom error types.", very confusing, first I think we should remove them from top level, then I fail to see how error module is suppose to hold custom error types, I don't get what you mean. The current situation is "I want create an error, ok so go shearch error, ok module error, ok Error, no error is not the error, it's Err, ok, and Err is not in error cause ???", it's totally intuitive. I can't explain nicely this in english, maybe taking example, almost every crate I know have an error module with a Error type that IS the true error type used in the crate. all thing related to error in nom should be in error module it's make sense, it's how user will except error thing to be. One could reexport them in top level but my personal taste is to avoid put too many thing in top level, I don't like much pub reexport of it's own crate.

I said `to_owned` make no sense cause the default error type changed for a structure Error (I love this approche) but these function are almost useless now no one is expected to use the tuple form.

I said convert feel useless cause cause it's for the tuple error form how I'm suppose to use it with Error ? And why there is a `usize` ? Again think as "I'm a user I search how to make the error owned I type error is search bar I get `ErrorConvert`" it's very unclear what is it.

**Comment by Stargateur** [comment]
With the add of `Error` struct that should probably named `Info` or something, in V6 we have `Err::Error<Error>` I think the problem here is clear it's should be something like `Error::Failure<Info>`. `Info` `Trace` or more I think think about it if you decide to agree to change this naming convention.

**Comment by Stargateur** [comment]
`IResult` => `NomResult` or `Outcome`,  `Output`. `IResult` is a strange name in rust.

**Comment by Stargateur** [comment]
plus I'm reading my own message seeing mistake you can clearly see my dyslexia in action, trust me that from my point of view all of naming look like a nightmare. Differentiate [`Err`](https://doc.rust-lang.org/std/result/enum.Result.html#variant.Err) from [`Err`](https://docs.rs/nom/6.2.1/nom/enum.Err.html#) from [`Error`](https://docs.rs/nom/6.2.1/nom/enum.Err.html#variant.Error) from [`Error`](https://docs.rs/nom/6.2.1/nom/error/struct.Error.html)

**Comment by Geal** [comment]
> Notice that for me all of this is kind of obvious, and I have tremendous difficulty to talk in English, I think I did make effort opening this, my purpose was "here what I find doing a little parser discovering V6" but you make my motivation go away with your strong word thing, I'm often use strong word, even if in my opinion nightmare in french is not that strong, at least at oral, do I need to add smiley to my sentence or do I need to take precaution at every sentence would make me even less likely to want to take 2 hours to write a message in English. Also, You didn't seem to be at all open to any change.

It is less obvious to me, because I know the API too well: common usability issues do not bother me as much. That's why I need to ask people to explain their experience.
About the strong word thing, I stand by it. Tone matters. Maybe your current work environment encourages it, but others don't.The title could have been written just as easily as "error type names are confusing and hard to search", the tone is more neutral, informative, and I'll see right away in the issue list what it is about.

As a side note, I'm french, so if it's easier for you to communicate in french, do it :)

> I don't understand your point about breaking change, my opinion about nom is that you are not afraid of breaking change and I love it. Sure, V5 to V6 is missing a guide but still I like see a crate change for better. You have probably the only crate in Rust that is used that much and going for a V7, THAT NICE. See https://0ver.org/. Of course I would not like a total breaking change, but renaming ? how easy is to just replace a identifier by another one ? Trust me the change in V5 => V6 was way harder to fix.

I can do breaking changes precisely because I think a lot about how much I can change without annoying users too much. This is an enormous amount of work: discussing with users, looking up usage in various crates, testing different APIs, helping some projects migrate. As you said, 5 to 6 was a hard migration, and as a result, most projects took a long time to do it (cf https://crates.io/crates/nom/reverse_dependencies and the download graph). So now is not the right time for big API changes and renaming. It will happen in nom 8.

I agree with your other points though. All those name are very confusing and should be changed. So I'll kickstart the work on that, probably first by gathering feedback on new names, and at the same time look at how it can synchronize with advances in the error WG (nom 6 changed its error management following some feedback there, but changes around std::error::Error were still too early)

**Comment by Stargateur** [comment]
> I'm french, so if it's easier for you to communicate in french, do it :)

I believe it would be not friendly to international community. I guess people could google trad it but meh, I prefer open talk and open talk in software world is in english.

> As you said, 5 to 6 was a hard migration, and as a result, most projects took a long time to do it (cf https://crates.io/crates/nom/reverse_dependencies and the download graph). So now is not the right time for big API changes and renaming. It will happen in nom 8.

Not logic and logic at the same time, a "no we not always make big breaking change", a strategy to make people not too angry ? You probably right here.

My SIP parser (yes I did a almost complete SIP parser in nom 4000 lines unfortunately that is not open source cause it's for a private company, advice don't do it SIP is horrible) is still in V5 because it's hard to migrate and I don't see a big need for it.

**Comment by cenodis** [comment]
I would have some concrete suggestions regarding the current error variants and their names.

Rename `Error` -> `Failure` and `Failure` -> `Invalid`. This would have the following advantages:
- We often say "the parser fails" but when it fails it usually means it returns `Error` and not `Failure` like one might from the names. Changing it would make the terminology more consistent.
- It removes the generic `Error` name and differentiates the variants from the standard `Error` type.
- It makes it more obvious what each variant means (`Failure` means the parser has failed to match the input, `Invalid` means the input is invalid and needs no further processing).


My second suggestion would be adding a new Variant to express that something is wrong with the parser chain itself (perhaps call it `Broken`?).
This would usually be the result of violating some part of a parsers contract. A good example would be passing max > min to a parser (#1333). Currently this is handled by making such parsers return `Failure`. Creating a new variant would have these advantages:
- Making this kind of error distinct from the error variant for invalid input would allow for more fine grained control over how such error are handled. This new error variant would be accompanied by combinators that allow translation from `Broken` to either `Error` or `Failure` allowing the user to specify exactly how the parser is meant to proceed.
- It avoids conflating the meaning of `Failure` with multiple error cases. (Invalid input, broken parser, ...?)
- It is much clearer to the user why the parser has failed to process the input. Making it easier to narrow down where the problem occurs and handle it appropiately.

**Comment by Stargateur** [comment]
I think:

- `Err` should be rename `Outcome`
- `Error` => `Failure`
- `Failure` => `Invalid` (More short than `Unrecoverable`)
- `IResult` => `NomResult` (IResult feel like a superset of result whereas NomResult make it more clear it from nom and make it more clear it's special)
- `ErrorKind` => `ParserKind`
- `E` generic `Context`

@cenodis (Using old name) I think an other solution would be to not use `E` for `Failure` but to introduce another generic, this clearly add a lot, but it's make sense, unrecoverable error is very rare and often have specific context.

In nom `Failure` is used for:

- Recursion limit https://github.com/Geal/nom/blob/485147144c8ac6d2ee278124cdddfc808aaa53df/fuzz/fuzz_targets/fuzz_arithmetic.rs#L37
- logical error https://github.com/Geal/nom/blob/e2a0dd52e07c6c55ab4ee7fad88e987a814a7a0f/src/multi/mod.rs#L364
- infinite loop https://github.com/Geal/nom/blob/e2a0dd52e07c6c55ab4ee7fad88e987a814a7a0f/src/multi/mod.rs#L744

That all and one was added recently. The current `ErrorKind` doesn't contain anything to express this.

**Comment by cenodis** [comment]
@Stargateur 
> Err -> Outcome, ErrorKind -> ParserKind

Sounds good.

> E generic -> Context

Generics have very short names (down to one letter) so I think its fine as is. The (usual) bound of that generic is already called `ParseError` which seems fine to me.

> IResult -> NomResult

Overall not a bad idea, `IResult` is not really that meaningful and if we are renaming stuff we might as well do that as well. Maybe `ParseResult` would be more accurate but more to type. But if people want less typing they can always use type aliases.

> logical error, infinite loop

The infinite loop and logical error to me both belong to the "broken parser" category. A parser that loops infinitely is obviously broken.

> Recursion limit

Im not sure this counts since that parser is not part of nom proper and only used as part of the test to prevent the fuzzer from feeding it input that would cause it to recurse until a stackoverflow (which I guess kind of counts as "invalid input"). Nom itself currently doesnt handle recursion limits at all.
 Special handling for recursion is already tracked in #1120 and would most likely exceed the scope of the other errors since it has to potentially track call depth across functions.

**Comment by Stargateur** [comment]
> Generics have very short names (down to one letter) so I think its fine as is. The (usual) bound of that generic is already called `ParseError` which seems fine to me.

yes I mean `E` => `C` for `Context`, Also  we also need to take a look at trait like `ParseError` `ContextError` `FromExternalError` `ErrorConvert`

> Overall not a bad idea, IResult is not really that meaningful and if we are renaming stuff we might as well do that as well. Maybe ParseResult would be more accurate but more to type. But if people want less typing they can always use type aliases.

`ParseResult`, I like it ! Maybe `ParserResult` ? yes it's a little long but it's 2 shorts word, I think it's ok, maybe also add a `PResult` shortcut
