### ISSUE TITLE
Help maintaining the crate

### ISSUE THREAD

**Issue by Stargateur** [Geal/nom#1420]
@Geal is alone to maintain nom and I would like to talk about it, this crate is a lot used and there is a lot of contribution (31 PR open, 141 issues). Unfortunately I believe @Geal don't have enough time to handle all alone. I think this hurt this crate. Indeed, the issues need to be clean. There is a lot of PR who need review.

I would like to propose myself to help, I don't have much experience in this kind of work but I would like to try. Even just temporary. If anyone want to propose someone else feel free.

**Comment by jamwaffles** [comment]
I'm sure Geal could use the help so obviously his choice in the end...

... but, IMO your abrasive tone in #1356 doesn't set a good precedent for representing this crate.

**Comment by Stargateur** [comment]
I'm very honest and speak my mind openly. If say "nightmare" is "abrasive tone" and I do not wish to represent the crate just maintain it, improve it. Gael say in this very issue it was hard to maintain the crate cause of time. And since this day, I tried to help in this matter. But I currently this feel useless cause Gael alone can do thing in the repository. I do think I have the skill to handle nom. I know what is important and require the Gael approval and what could be trivial enough to not bother gael.

Also, avoid use "..." cause that also not very kind either.

**Comment by Geal** [comment]
@stargateur while I understand your position (and I've had my own thoughts on how to scale the project), I would have appreciated if you reached out to me privately to discuss it first.
I did not have much time these past years for various reasons, but my situation is changing and I'd expect to be more available right now. 

That said, the crate is not unmaintained, there are regular releases and bugfixes. nom has steadily improved over the years and has been serving quietly a lot of other projects.
Looking just at the number of issues and PRs gives you an incomplete picture: from the beginning, nom has been setup to make everything public, so users can build upon it, make their own toolbox, replace some combinators, etc. Most of those PRs are for new features, while I'm actively trying to remove features and extract them in more specifc crates. So I put off integrating a lot of code because I lack time, yes, but if they're compelling enough I'll do the integration work and merge them. I've always done it.

As for your tone, I agree with what @jamwaffles said, I do not feel it is appropriate to represent this project.
Being honest, speaking your mind, or having difficulties speaking english, have never been excuses to be rude, even if it is not your intent.
So I'd appreciate it if you took the time to improve the way you talk to contributors, as it will be useful both here and for your professional life.

Btw my name is Geoffroy, not Gael, @Geal is my github handle.

**Comment by mohe2015** [comment]
I'm not actively following development here but only using this crate but isn't it also possible to help as a contributor by reviewing PRs etc? So basically doing most of it except merging.

**Comment by Stargateur** [comment]
> I would have appreciated if you reached out to me privately to discuss it first

That common in open source project to open an issue for that, I'm for open discussion. you even just said "nom has been setup to make everything public".

> That said, the crate is not unmaintained, there are regular releases and bugfixes. nom has steadily improved over the years and has been serving quietly a lot of other projects.

not what I mean, I just often read that you don't have much time and the current situation show that.

> I did not have much time these past years for various reasons, but my situation is changing and I'd expect to be more available right now.

Well, so this issue seem closed
