### ISSUE TITLE
Limitation of the alt! combinator

### ISSUE THREAD

**Issue by wenLiangcan** [Geal/nom#143]
`tag!`s in `alt!` can only be arranged in ascending order of their lengths.

```rust
named!(lang1, alt!(tag!("rust") | tag!("c")));
named!(lang2, alt!(tag!("c") | tag!("rust")));

assert_eq!(lang1(b"c"), Incomplete(Size(4)));
assert_eq!(lang2(b"c"), Done(b"", b"c"));
```

**Comment by Geal** [comment]
Hi,

This is an expected behaviour of `alt!`: if one of the child parsers returns `IResult::Incomplete`, it will return `IResult::Incomplete`. Here, in the first test, you pass a single char to a `tag!` that expects 4 chars. In the next version of nom, there will be a tag implementation that can make decisions based on a limited input.

In the meantime, if you don't care about handling the partial input case, you can write your parser like this:

```rust
named!(lang1, alt!(complete!(tag!("rust")) | complete!(tag!("c"))));
```

The `complete!` combinator will transform a `IResult::Incomplete` from the child parser in an `IResult::Error`.

**Comment by wenLiangcan** [comment]
Oh I see, thank you very much!
