### ISSUE TITLE
Pseudo mailing list to discuss the project and it's future.

### ISSUE THREAD

**Issue by cheako** [Geal/nom#1472]
There are a number of users and as the project isn't big enough to have an IRC channel or making list...  I made this issue to function as a makeshift making list/forum.

I can be found on Matrix as @cheako:matrix.org and perhaps I'll start a nom channel if we need to have a meeting.

These issues are relatively new and if I mention them the participants will hopefully be invited:
https://github.com/rust-bakery/nom-bufreader/issues/9#issuecomment-989459539
https://github.com/Geal/nom/issues/1468
https://github.com/Geal/nom/issues/1464
https://github.com/Geal/nom/issues/1459

**Comment by Geal** [comment]
maybe you should ping me privately before opening issues like that. While I appreciate that people care enough about nom to think about its maintenance, it is not actually unmaintained. There was a release just one month ago. Ad if I have not been active here during that month, it is because I am busy preparing releases for other projects.
If you want a venue to discuss about nom, you can go to gitter, there are people there regulrly chatting and helping each other: https://gitter.im/Geal/nom

**Comment by cheako** [comment]
I didn't know there is a way to ping ppl privately...

**Comment by Geal** [comment]
I am not hard to find. email, twitter, irc, etc.
