### ISSUE TITLE
why does empty input in alpha, digit, hex_digit, ... in nom.rs return error

### ISSUE THREAD

**Issue by tstorch** [Geal/nom#217]
I'm not quit sure why this is the case. Speaking mathematically every character in an empty string satisfies every condition. The check for empty input is wrong here imho and should be take care of by the caller. Or are there other technical reasons, why this is the way it is?

**Comment by Geal** [comment]
There was a reason, but I don't remember it very well. I think it was that alpha and others actually expect to match some characters, and that the potential absence of characters needed to be handled elsewhere, with combinators like `opt!`

**Comment by tstorch** [comment]
Ok. I'll take a look at it and try to figure this out...

Is there a reason, why `many` and `separated_list` have both versions, i.e. one possibly empty list and one with at least one element and `alpha`, `digit`,... don't?

**Comment by Geal** [comment]
Ok, so this behaviour appeared in 2eddc3d9 and comes from issue #142. There is also the issue #226 about that behaviour.

So there are three possible solutions there:
- the actual behaviour, `space` and other functions expect some input, so throw an error
- what you propose, considering that an empty input is correct
- what is proposed in #226 by @ketralnis, considering that an empty input is an incomplete input

I think the actual behaviour is wrong, because there could be some future valid input, so I lean more on @ketralnis's solution, returning `Incomplete` for this.

I'll have to test it on current projects using nom, though, because this has the potential of breaking a lot of code.

**Comment by tstorch** [comment]
That sounds like a reasonable, also I'm not completely sold on that idea. For me the ideal solution would be to have two macros where there ist currently one, i.e. `alpha` (accepts empty input) and `alpha1` (returns incomplete on empty input). Not accepting empty input in the current form is counterintuitive from a general perspective.

**Comment by Geal** [comment]
Fixed in 7ee5d15. The functions now return `Incomplete` on empty input. The `complete!` combinator must be used in cases where it's ambigous.

**Comment by tstorch** [comment]
@Geal To be honest: It feels strange, that an empty input and a completely parsed input, i.e. completely alphabetic input for alpha, return completely different results (i.e. Incomplete for empty and Done for completely alphabetic). There has to be a better way.

My point of view is still: alpha should accept an empty input as legal. Another macro, e.g. alpha1, then could wrap this and return an error length 0.
