### ISSUE TITLE
Missing documentation on documentation

### ISSUE THREAD

**Issue by GuillaumeGomez** [Geal/nom#227]
I went through a few macros and almost every time, I found the lack of examples really problematic (like [here](http://rust.unhandledexpression.com/nom/macro.separated_list!.html) for example).

**Comment by dashed** [comment]
Having the same problem :cry:

**Comment by mbr** [comment]
While I like the crate, the docs are just incredibly ineffective. Rust macros don't exactly produce nice error message and the docs are little help. Missing in particular:

1. A nice example in the README (or at least the root docs), showing a *simple*, **complete** program (how am I supposed to get my parsed data out of the parser)?
2. An example `u8` vs `&str`
3. For every macro there should be one, better *two* examples illustrating how it works.

My apologies if this seems a bit crass, but usually, I find myself working on the parser for 5 minutes out of 60 and spending the remaining fighting nom, trying to find an example from *somewhere* to get it working.

I'd love to contribute a few examples, but I'm not sure I can even write proper ones at this point. =/

**Comment by Geal** [comment]
@GuillaumeGomez @dashed @mbr could you provide a bit more info on what you would need from the documentation? Adding examples for each macro is a clear enough target, but the rest is not so clear.
Did you find the articles in the [wiki](https://github.com/Geal/nom/wiki)? If not, why? Were they helpful?
What is wrong with the examples in the readme? There's another one in [the online documentation](http://rust.unhandledexpression.com/nom/), is it alright? There are other complete examples in the [tests](https://github.com/Geal/nom/tree/master/tests), should those be used instead?

What do you mean with an example of "how to get data out of the parser"? You usually pattern match on `IResult`, which is specified [here](http://rust.unhandledexpression.com/nom/enum.IResult.html). Do you need something else?

I would really like to improve the documentation, but I have limited time to do it, so I would really appreciate precise feedback here, otherwise the docs won't improve much.

**Comment by alanhdu** [comment]
Just me two cents from using nom:

1. The docs are scattered in a couple different places. I didn't even know about that there was documentation on the wiki until I saw this issue.
2. The iso8601 tutorial (https://fnordig.de/2015/07/16/omnomnom-parsing-iso8601-dates-using-nom/) was super helpful for seeing how everything fits together. Something like this would be great for official docs (it'd be nice to parse something a little more substantial though).
3. There are variants for `named!` that I couldn't find documentation for (for example `named!(blah<i32>, ...)`

**Comment by mbr** [comment]
FWIW, I'm not 100% sure this is an issue with nom itself. Rust's macro error messages just tend to become utterly unreadable (at least today) compared to "regular code".

**Comment by Geal** [comment]
@GuillaumeGomez so, is the documentation documented now? :)

**Comment by GuillaumeGomez** [comment]
https://docs.rs/nom/4.0.0/nom/macro.eof.html -> "TODO: example" 😛 

Please add a `#![deny(missing_docs)]` and then I guess I'll consider it as done. Thanks a lot for your work, it's truly amazing!

**Comment by Geal** [comment]
closing this in favor of #914
