### ISSUE TITLE
Tcp socket

### ISSUE THREAD

**Issue by Yamakaky** [Geal/nom#246]
Is it possible to directly plug a TCP socket to a nom parser? Something like a TcpProducer.

**Comment by Geal** [comment]
That should not be too hard, considering there's already a `FileProducer`. Something more general, like a `ReadProducer`, would be great, but I do not have the time to handle it right now, would you like to try developing that?

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
