### ISSUE TITLE
Translating parsers across input types?

### ISSUE THREAD

**Issue by fitzgen** [Geal/nom#266]
### Problem I've been running into

All the basic building block parsers (eg `le_u32`) only work on inputs of `&[u8]`. However, my input type is not `&[u8]`, it is a composition of `&[u8]` and some extra carry-along data that helps guide my parsing[0]. Therefore, I find myself repeatedly unwrapping and rewrapping the input part of `IResult`s whenever I need to call one of these basic building block parsers. This is a surprisingly large amount of boilerplate and match statements.

_[0] In this case, I am parsing DWARF's Debugging Information Entries (DIEs), whose properties, types, and general shape is encoded in abbreviations, which must be parsed first. The grammar is not context free, it is essentially encoded in the abbreviations. Therefore, my input is basically `(&[u8], &AbbreviationDefinitionTable)`._
### Hacky thing I've come up with

Ideally this would be a combinator that returns a new parser, but I haven't been able to make that work without the upcoming `return impl Trait` Rust feature, so instead it takes the input and eagerly parses it instead.

This one is a bit of a doozy... We are lowering the composed input type to the basic input type (`&[u8]`) and then running the basic building block parser, and then raising the resulting `IResult<LowerInput, ...>` back into the composed input type `IResult<HigherInput, ...>`.

``` rust
fn translate_domain<Output,
                    Error,
                    HigherInput,
                    LowerInput,
                    LowerParser,
                    Unwrap,
                    Rewrap>(input: HigherInput,
                            parser: LowerParser,
                            unwrap: Unwrap,
                            rewrap: Rewrap) -> IResult<HigherInput, Output, Error>
    where Unwrap: Fn(HigherInput) -> LowerInput,
          Rewrap: Fn(HigherInput, IResult<LowerInput, Output, Error>) -> IResult<HigherInput, Output, Error>,
          LowerParser: Fn(LowerInput) -> IResult<LowerInput, Output, Error>,
          HigherInput: Clone
{
    let lower_input = unwrap(input.clone());
    let lower_result = parser(lower_input);
    rewrap(input, lower_result)
}
```

Is there a better way? Is there a canonical name for this sort of operation? (I feel like Haskellers probably have a name...)
### Alternative?

I think all this could be unnecessary if `le_u32` et al were generic and took something kind of like `AsRef<[u8]>` instead of `&[u8]` directly. But then that "something" would also have to implement the rewrapping/raising back into the higher input type. Something like this?

``` rust
pub trait Translatable<ToFrom> {
    fn lower_to(&self) -> ToFrom;
    fn raise_from(lowered: ToFrom, original: Self) -> Self;
}
```

Is this something you might be interested in implementing for `le_u32` et al? Am I way off the rails here? Am I the only person that doesn't use `&[u8]` as my input type?

Thanks!

**Comment by Phlosioneer** [comment]
> (I feel like Haskellers probably have a name...)

I'm not a regular in the functional programming community, but I believe this is called flat-mapping.

It's the idea where you have a container, and you want to apply a function to the thing inside the container, but the output is _no more complex_.

For example, if you had:

``` Rust
fn maybeDoSomething<T>(x: T) -> Option<T> {Some(x)}

fn main {
  let something: u8 = 20;
  let maybe: Option<u8> = Some(20);
  let why_so_complex: Option<Option<T>> = maybeDoSomething(maybe);
}
```

Here there's an option of an option. Kinda pointless, right? So, in the option type, you define this:

``` Rust
impl<T> Into<Option<T>> for Option<Option<T>> {
  fn into<T>(self: Option<Option<T>>) {
    match self {
      Some(Some(x)) => x,
      Some(None(x)) => None,
      None(_) => None
    }
}

```

And now, you can get rid of that messy `Option<Option<u8>>`!

However, this isn't very portable. For one thing, you have to declare the type youself to be able to implement this. So rust has a different way: Iterators. If you look at [std::option::Option](https://doc.rust-lang.org/std/option/enum.Option.html), you'll see that it defines an iterator over one or no elements, so that this kind of no-redundencies behavior can happen.

The concept is either called mapping or flat-mapping. I think it's mapping. Anyway, whatever container you're using, maybe you can use this technique to work with map(). You could define Iter on a wrapper type around your (&[u8], &AbbrevTable) and an IntoIterator/FromIterator pair, and map() should work properly on it. Then you just have to tell the parsers to use map() and it should work! That'd mean your main type would be `IResult<iterWrapper::IntoIter, iterWrapper::IntoIter>`, where iterWrapper is a struct with a &[u8] and an &AbbrevTable.

Either the map!() parser does that map() invocation, or you just make a small conversion parser that just changes types - no code needed!

**Comment by Phlosioneer** [comment]
Clarification: The type that your iterator resolves to should be u8 or some reference/permutation thereof. Otherwise map will have a type error. You can't map a `foo(u8)` over an `Option<[u8]>`. At least, not with Option's iterator. [] might actually have an iterator for map.

**Comment by Geal** [comment]
@fitzgen could you provide examples of the parsers you are writing? I might get a better feel of what you need.
If you need to carry context as you advance on the input, the [method](https://github.com/Geal/nom/blob/master/src/methods.rs) approach could be nice. With this, you make a struct carrying the context, and the parsers are methods of that struct, that can access its attributes.

**Comment by fitzgen** [comment]
Sorry it has taken me a bit of time to get back on this -- I was on vacation.

https://github.com/fitzgen/gimli is my project. Very much in progress and flux at the moment.

https://github.com/fitzgen/gimli/blob/1a3dd139633c622ef8007c8236d2d2c203de2b12/src/parser.rs#L855-L864 is the generic trait for translating parsers across inputs.

https://github.com/fitzgen/gimli/blob/1a3dd139633c622ef8007c8236d2d2c203de2b12/src/parser.rs#L911-L1036 is the implementation of translating parsers across inputs, leveraging those traits above.

https://github.com/fitzgen/gimli/blob/1a3dd139633c622ef8007c8236d2d2c203de2b12/src/parser.rs#L866-L901 and https://github.com/fitzgen/gimli/blob/1a3dd139633c622ef8007c8236d2d2c203de2b12/src/parser.rs#L1488-L1496 is some example usage of the machinery where how I parse the underlying `&[u8]` input depends on my current `Format` which is either `Dwarf32` or `Dwarf64` and changes the sizes of various serialized fields and itself can change across compilation units.

**Comment by Geal** [comment]
@fitzgen with the recent work around input traits, can it work for you? I have [an example](https://github.com/Geal/nom/blob/master/tests/blockbuf-arithmetic.rs) of custom input type, reusing a BlockBuf.

**Comment by fitzgen** [comment]
Yeah, as we talked about at rustconf, I think the biggest thing was not being able to use currying and/or returning closures to create custom parser functions. When `return impl Trait` is available/stable I think most of the pain I experienced will go away.

That example looks pretty good, too. I think it could use a bunch of comments for readers trying to figure out what's going on, if you're going to point to it from documentation as an official tutorial/example for people using custom input types.

Generally, it would be great if every helper / mini parser that `nom` provides worked only with those traits (I think this is the direction you're going / have gone), because not using `&[u8]` as an input type made a lot of them unavailable.

Not sure if it is worth keeping this issue open anymore, feel free to close it unless you want to evolve it into some concrete work item or whatever.

**Comment by ncalexan** [comment]
> Generally, it would be great if every helper / mini parser that nom provides worked only with those traits (I think this is the direction you're going / have gone), because not using &[u8] as an input type made a lot of them unavailable.

I have a similar situation: I'd like to parse a sequence of tokens that aren't directly represented as `&[u8]`.  (In my case, I want to parse EDN data structures, which is morally equivalent to parsing JSON data structures.)

**Comment by Geal** [comment]
@ncalexan you need to parse EDN metadata separately? Working with token streams is something that worked in a few tests I did before, but I have not had the time to make a complete example. In any way, if it does not work, I'd like to fix it, because that's a use case I want to support.

What would be the type of your token stream? It needs to implement those traits to work with nom: https://github.com/Geal/nom/blob/master/src/traits.rs

there might be a need for specific combinators for token streams, we'll see how it goes.

**Comment by ncalexan** [comment]
> @ncalexan you need to parse EDN metadata separately?

No, I don't think so.

> Working with token streams is something that worked in a few tests I did before, but I have not had the time to make a complete example. In any way, if it does not work, I'd like to fix it, because that's a use case I want to support.

OK, that's nice to hear.
 
> What would be the type of your token stream? It needs to implement those traits to work with nom: https://github.com/Geal/nom/blob/master/src/traits.rs

I guess my type would be some union thing that looks a lot like JSON:
```
pub enum Value {
  Nil,
  Keyword(String),
  Integer(i64),
  String(String),
  ...,
  List([Value]),
  ...
}
```
We want to parse say `[Value::Keyword(":find"), Value::String(field)]` into some other structure.

The requirement to be byte- or char-like is a pretty hard blocker for parsing token streams.  I stopped trying when I started digging into the existing combinators and saw how byte-oriented they really were.

> there might be a need for specific combinators for token streams, we'll see how it goes.

I couldn't figure out what the equivalent of `tag!` is for an arbitrary token.  That is, given input `I = [T]`, is their a combinator with signature `literal(T) -> (I -> IResult<I, O, E>)`.

(Apologies for my pidgin Rust -- I have read a little but written almost none.)

**Comment by Geal** [comment]
which combinators did you read? Some of them handle char or byte specific use cases, but most of them are independent from the input type (cf https://github.com/Geal/nom/blob/master/src/sequence.rs or https://github.com/Geal/nom/blob/master/src/multi.rs for example). They still need a way to count substream length and advancement in the original input stream, but that's not specific to bytes or chars.

That said, it should be quite easy to make a combinator taking a pattern that recognize a specific token or a token slice, extracts some values and builds a result. I don't see yet how the syntax would look like:

```
struct Find {
  data: String
};
// could be written as named!(key_value_string<&[Value],Find>,
fn key_value_string(tokens: &[Value]) -> IResult<&[Value], Find> {
  extract!(tokens,
    [Value::Keyword(":find"), Value::String(field)],
    value!(Find { data: field })
  )
}
```

I'm not sure `extract` is the right word here. Could `match` be used for a macro name? The `value!` combinator does not consume input, and returns whatever argument has been passed. Here, since field appears in the scope of the pattern matching, `value!` could refer to it.

Such a combinator could then be used with `do_parse!`, `pair!` or `many0!` without any issue.

**Comment by ncalexan** [comment]
> which combinators did you read? Some of them handle char or byte specific use cases, but most of them are independent from the input type (cf https://github.com/Geal/nom/blob/master/src/sequence.rs or https://github.com/Geal/nom/blob/master/src/multi.rs for example). They still need a way to count substream length and advancement in the original input stream, but that's not specific to bytes or chars.

Sorry, I must be missing something.  When I look at, for example, https://github.com/Geal/nom/blob/master/src/traits.rs#L142 I see that the basic `InputIter` assumes that the underlying items can be identified with characters (`AsChar`).  I can see that I can map my parsed token stream back to a textual representation, but that's incredibly inefficient.  Are these traits in fact not needed?

**Comment by Geal** [comment]
those traits are needed, but they have different goals. `InputLength`, `InputTake`, `Slice`, `FindToken` and `FindSubstring` are useful for any input type. `Compare` has a specific method for caseless comparison, so that's more byte and char oriented. `InputIter` is there to abstract the differences between `&[u8]` and `&str`.

In your case, you could get away with implementing `InputLength`, `InputTake`, `Slice` and only using the combinators you need.
