### ISSUE TITLE
alt!() is not commutative

### ISSUE THREAD

**Issue by filipegoncalves** [Geal/nom#29]
I came across something interesting when writing a parser to match a string literal with escape sequences.

Consider this code:

```rust
// ~~~ String literal parser and auxiliary parsers ~~~
named!(not_escaped_seq<&[u8], &[u8]>, take_until_either!(&b"\\\""[..]));
named!(escaped_seq, alt!(tag!("\\r") | tag!("\\n") | tag!("\\t") | tag!("\\\"") | tag!("\\\\")));
named!(string_literal<&[u8], String>,
       chain!(
           tag!("\"") ~
           s: many0!(map_res!(alt!(escaped_seq | not_escaped_seq), from_utf8)) ~
           tag!("\""),
           || {
               syntax::parse::str_lit(&s.into_iter().fold(String::new(),
                                                          |mut accum, slice| {
                                                              accum.push_str(slice);
                                                              accum
                                                          })[..])}));
```

It matches string literals that can contain any of the escaped sequences listed in `escaped_seq`. This parser works as expected, however, switching the order of the options in `alt!(escaped_seq | not_escaped_seq)` makes the parser unable to recognize any string literal that contains at least an escape sequence.

That is, replacing this line:

```rust
           s: many0!(map_res!(alt!(escaped_seq | not_escaped_seq), from_utf8)) ~
```

With:

```rust
           s: many0!(map_res!(alt!(not_escaped_seq | escaped_seq), from_utf8)) ~
```

Breaks the parser. Here are 2 test cases:

```rust
    #[test]
    fn single_str_scalar_value() {
        let input = &b"\"a string literal\""[..];
        let res = str_scalar_value(input);
        assert_eq!(res, Done(&b""[..], "a string literal".to_string()));        
    }

    #[test]
    fn single_str_scalar_value2() {
        let input = &b"\"A backslash in quotes: \\\"\\\\\\\"\""[..];
        let res = str_scalar_value(input);
        assert_eq!(res, Done(&b""[..], "A backslash in quotes: \"\\\"".to_string()));       
    }
```

The former passes with both versions; the latter fails with the 2nd version of the parser (the parser returns an `Error`). In general, any string with an escaped sequence is not recognized by the 2nd version of the parser.

Shouldn't `alt` be commutative?

**Comment by Geal** [comment]
From what I understand, the second test tries to parse `"A backslash in quotes: \"\\\""`. `not_escaped_seq` parses `A backslash in quotes: `, then stops at `\"`, because it is a `take_until_either` on `\` or `"`. The problem is the same as the bug with alpha: on every following run, `take_until_either` will return an empty string (I think), which will stop `many0`.
The remaining input will be `\"\\\""`, which the second `tag!("\"")` cannot parse.

`not_escaped_seq` is more general than `escaped_seq`, so they cannot be swapped easily.

**Comment by filipegoncalves** [comment]
Yes, from what I saw this is exactly what is happening. So at the end of the day, is it a bug or not?

I might check it on parsec when I have the chance for the sake of consistence. It was really not intuitive at all to realize that the parser would work just by switching the order of the parsers inside `alt`.

**Comment by Geal** [comment]
I do not think that parsers are naturally commutative. In a lot of cases, the order in which you apply them will affect the precedence rules in the grammar.

The `alt!(tag!("\\r") | tag!("\\n") | tag!("\\t") | tag!("\\\"") | tag!("\\\\"))` might be an exception, because they all recognize two characters exactly, and the languages they recognize are disjoint.

Here are some examples of parsers that cannot commute:

- `tag!("abc")` and `is_a!("abc")`
- `take!(4)` and `take!(5)`

**Comment by filipegoncalves** [comment]
Ah, right. I get it now.

Thanks for your help.
