### ISSUE TITLE
Consumer and State

### ISSUE THREAD

**Issue by theduke** [Geal/nom#309]
I need to keep track of position in the input stream (byte offset, line and column number).

I guess Consumer with ConsumerState would be the way to go,
but I'm having a hard time wrapping my head around / understanding it.

Could you provide an explanation how Consumer/ConsumerState work and how I could approach my problem?

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
