### ISSUE TITLE
Stdin producer

### ISSUE THREAD

**Issue by Yamakaky** [Geal/nom#311]
Did you consider adding a producer for stdin? It could be very handy, especially when combined with a stdout consumer.

**Comment by jpastuszek** [comment]
Hi, I needed this as well. I have tried to implement this with `Consumer`/`Producer` but this is way to complicated...
I have implemented `ReadStreamBuf` struct in my project that will let you apply any parser to any `Read` source (stdin, file, socket, etc.). I have learned post-factum that `chomp` crate uses same approach:

https://github.com/jpastuszek/varnishslog/blob/master/src/stream_buf.rs

Usage is like that:

```rust
    let stdin = stdin();
    let stdin = stdin.lock();
    let mut stream = ReadStreamBuf::new(stdin);

    loop {
        match stream.fill_apply(my_parser) {
            Ok(None) => continue, // try again with blocking read
            Ok(Some(record)) => do_stuff(record),
            Err(err) => {
                panic!(err)
            }
        }
    }
```

**Comment by flip111** [comment]
Expected this to be there out of the box, since stdin is one of the most common streams. How is the streaming feature suppose to work?

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
