### ISSUE TITLE
FileProducer ignores Move(Consume(..)) if the ConsumerState is Done

### ISSUE THREAD

**Issue by jugglerchris** [Geal/nom#332]
I think this is moot, given the comment about futures on #286...

I was trying to use a `FileProducer` more than once with two `Consumer`s in sequence.  The first one returns a few things (with `ConsumerState::Continue`), and when it's done returns `Done(Consume(..))` having consumed a terminator.  `FileProducer` ignores that `Move` inside `Done`, which means that the next consumer starts at the wrong position.

Easy workaround (I return `Continue` first and set a flag to return `Done` next time around), so I'm not worried, and it's possible I'm misusing the producer, but thought I should mention it for completeness.  :-)

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
