### ISSUE TITLE
FileProducer gets confused by large Incomplete

### ISSUE THREAD

**Issue by jugglerchris** [Geal/nom#351]
I have a consumer which needs an unbounded maximum size of data.  (E-mail headers; I've seen a References: line of 16k!); it's fed from a `FileProducer`.

When the `FileProducer`'s buffer is full (say 8192 bytes in my case) but the consumer returns `Await(8194)`, say, things go wrong; `FileProducer` tries to refill, reads 0 bytes into the remaining space, and then the consumer is given `Eof(input)` without getting any more data.  I think this is probably a bug.

I was hoping that I could watch the return value from `FileProducer::apply` in the caller and call `resize` as needed, but by that time it's too late.  Do I have a better option that making my own producer, suspiciously similar to `FileProducer` but which auto-grows the buffer?  If that's functionality you'd be interested in adding (presumably optionally), I'm open to implementing it and sending a PR.

**Comment by bovee** [comment]
I've also hit this issue and my solution was to throw an explicit error when this happens (see https://github.com/bovee/nom/tree/producer_erroring). I had to add an `Error` option to the `Input` enum though which might not be the most elegant solution and requires updating downstream code to handle the extra `match` condition :/ .

I would love to see a better solution (and an auto-growing buffer would be great for my use-case too as long as it had some definable upper limit).

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
