### ISSUE TITLE
Non-u8 slices as input

### ISSUE THREAD

**Issue by lord** [Geal/nom#380]
Is it possible to use non-u8 slices as input? I almost thought it was possible, but this example:

```rust
#[derive(Debug)]
enum Foo {A, B}
named!(parse<&[Foo], &[Foo]>, take!(1));
fn main() {
    println!("{:?}", parse(&[Foo::A]));
}
```

complains that:

```
error: no method named `slice_index` found for type `&[Foo]` in the current scope
```

It looks it's complaining because my type `&[Foo]` type doesn't implement the [`InputIter`](https://github.com/Geal/nom/blob/844edaff8a21ee2e3662ef3f3ce3919547f94ef9/src/traits.rs#L141-L155) trait. I'd implement it myself, but `&[Foo]` is a slice, not a type I've created, so I can't implement traits from other crates for it.

Am I doing something wrong, or is using nom this way simply not supported? (I've looked through as much of the docs and past issues as I could, and couldn't find anything, but sorry if this information is already listed elsewhere — I'm somewhat new at Rust!)

**Comment by Geal** [comment]
nom uses a set of traits that an input type must handle. See https://github.com/Geal/nom/blob/59ab26ec982e2f069f715fdea7458195998d85a7/tests/blockbuf-arithmetic.rs as an example.

Right now, I have implemented those directly for `&[u8]` and `&str`. The `&[u8]` version was done instead of `&[t]` because there are optimisations to be done for bytes.

Unfortunately, there are two issues here:
- the orphan rules say you can't implement a trait you didn't define for a type you didn't define
- until specialization lands in rust stable, I can't ship implementations for both `&[u8]` and generic `&[T]`

There's something that you can try, still: define an input type as `struct Input(&[Foo])` and implement the traits on `Input`. The traits are defined here: https://github.com/Geal/nom/blob/master/src/traits.rs
Depending on what your `Foo` type does, a few of those traits won't make much sense and should get a dummy implementations: `AsChar` and `Compare::compare_no_case`

The input traits are a new thing in nom, which is why there's not much written about it yet. I'd like to see your use case work here, so please try with the method I gave you, and let me know if you encounter any issues.

**Comment by lord** [comment]
Prime, thanks! I'll report back when I get the chance to implement this.

**Comment by lord** [comment]
Although it's perhaps slightly unwieldy, it works. Thanks!
