### ISSUE TITLE
construct FileProducer from Path

### ISSUE THREAD

**Issue by vandenoever** [Geal/nom#381]
`std::io::File` is created with `open<P: AsRef<Path>>(path: P)` while `FileProducer` accepts a byte slice. It would be nice to have a constructor that accepts `Path` instances like `File` does. Converting a path to a string is a non-negligible cost on applications that parse the contents of whole directories recursively.

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
