### ISSUE TITLE
permutation that supports more than 8 combinators

### ISSUE THREAD

**Issue by log0ymxm** [Geal/nom#402]
I notice that there is the following used in the `permutation` combinator,

```rust
// HACK: for some reason, Rust 1.11 does not accept $res.$it in
// permutation_unwrap. This is a bit ugly, but it will have no
// impact on the generated code
#[doc(hidden)]
#[macro_export]
macro_rules! acc (
  (0, $tup:expr) => ($tup.0);
  (1, $tup:expr) => ($tup.1);
  (2, $tup:expr) => ($tup.2);
  (3, $tup:expr) => ($tup.3);
  (4, $tup:expr) => ($tup.4);
  (5, $tup:expr) => ($tup.5);
  (6, $tup:expr) => ($tup.6);
  (7, $tup:expr) => ($tup.7);
);
```

https://github.com/Geal/nom/blob/e5da7f1753629a30a39e067d06a6d033e53d8640/src/branch.rs#L459

Is this a limitation that no longer exists after rust 1.11, or is it still a problem in 1.12, 1.13, and onward?

The permutation operator is a bit complex, I assume that it has to try each combinator over and over until it finds a permutation that works, else it fails. Is that correct? I'd expect that long permutations will generate quite a bit of code. Is it even wise to have a long permutation in a parser?

**Comment by Geal** [comment]
Hi!

You're right, that's how permutation works here. Compared to other parsers, this one will generate code that's kind of flat:

- create a tuple of `None` values: https://github.com/Geal/nom/blob/e5da7f1753629a30a39e067d06a6d033e53d8640/src/branch.rs#L380 
- unwrap all the options: https://github.com/Geal/nom/blob/e5da7f1753629a30a39e067d06a6d033e53d8640/src/branch.rs#L412
- this is where the most code is generated: https://github.com/Geal/nom/blob/e5da7f1753629a30a39e067d06a6d033e53d8640/src/branch.rs#L387 but for each child parser it only generates this: https://github.com/Geal/nom/blob/e5da7f1753629a30a39e067d06a6d033e53d8640/src/branch.rs#L502-L517

I could support more than 8 combinators, but I won't remove that hack right away, since I plan to support older versions of Rust for some time. I have not tested if the hack is still needed anyway.

**Comment by Geal** [comment]
which kind of format do you have with a large number of permutations?

**Comment by Geal** [comment]
I just bumped the number of child parsers to 20, I hope it will be enough :) d8b2e57
