### ISSUE TITLE
Is do_parse! + opt! broken?

### ISSUE THREAD

**Issue by danielbodart** [Geal/nom#406]
Should this work?

```
named!(a_bug <(&[u8], Option<&[u8]>)>, do_parse!(
    a:tag!("a") >>
    b: opt!(tag!("b")) >>
    ((a, b))
  ));

#[cfg(test)]
mod tests {
    use nom::IResult::Done;

    #[test]
    fn a_bug() {
        assert_eq!(super::a_bug(&b"ab"[..]), Done(&b""[..], (&b"a"[..], Some(&b"b"[..]))));
        assert_eq!(super::a_bug(&b"a"[..]), Done(&b""[..], (&b"a"[..], None)));
    }
}
```

**Comment by log0ymxm** [comment]
If you're using nom 2.0 it's this issue: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_2.md#parsers-returning-incomplete-instead-of-an-error-on-empty-input

It can be fixed by adding a complete inside the `opt!`:
```rust
named!(a_bug <(&[u8], Option<&[u8]>)>, do_parse!(
    a:tag!("a") >>
    b: opt!(complete!(tag!("b"))) >>
    ((a, b))
));
```

**Comment by danielbodart** [comment]
Okay that works but still seems like a bug to me (principle of least suprise etc). 

Surely opt! should always convert incomplete into None?

**Comment by log0ymxm** [comment]
I'd think that makes sense, it can be tricky to recognize what's going wrong there. I only know due to recently having to deal with the issue in upgrading to nom 2.0.

I can't comment exactly on any technical reasons why it was changed, but it looks like it might be a consequence of these issues #217 and #226, found through the nom 2.0 tracking issue.

**Comment by log0ymxm** [comment]
Just noticed that the `opt!` macro is specified to return "`Incomplete` if it did not have enough data to decide".

**Comment by Geal** [comment]
@danielbodart I agree with the principle of least surprise, but here, the real surprise does not come from nom's operators, it comes from the underlying use case: working on data streams like network sockets or buffered files.

If your parser must recognize an optional `"abcd"`, but the TCP packets chunk it in `"ab"` then `"cd"`, the parser should tell you that it does not have enough data to decide with `"ab"`, because if it returns `None` already, then it will not interpret `"cd"` correctly, although the data is correct.

I tried with nom to make robust parsers, and incomplete data is one of the biggest sources of errors.

**Comment by danielbodart** [comment]
Hmmm that sounds sensible but I think you actually have a broken grammar IMHO, you should never end with a trailing opt in a grammar for exactly this reason. 

I'm actually using nom for parsing HTTP exactly according to the RFC and there is not a single case in the whole grammar that I don't have to force opt!(complete!(...)) and I test with fragmented data. 

I've used many parser combinator libraries and am the author of a couple (in Java) and have never come across an optional combinator that isn't optional!

**Comment by Geal** [comment]
I was not talking about a trailing opt. This could happen right in the middle of your format. If you don't believe me, let's take a look at a case in your HTTP parser (I'm not familiar with your code, so there may be issues I have not seen, but I trust you'll get the point):
this line has a `opt!(complete!`: https://github.com/danielbodart/http-handler.rust/blob/master/src/grammar.rs#L100
and the result is used in: https://github.com/danielbodart/http-handler.rust/blob/master/src/grammar.rs#L111

let's say you get the header `Accept-Encoding: gzip, deflate\r\n`, but with the value chunked like this:

-  `gzi`
-  `p, d`
-  `eflate`

Since this parser ends up merging all the subslices (and the content of this header is not particularly meaningful), it won't have an effect in the end, but let's see how the individual parts will be recognized by `field_vchar`: `gzi`, `p,`, `d`, `eflate`.

While in that case, you would like to see: `gzip,`, `deflate`.

That's why, if you cannot work on the complete data at once, the optional part should contain a terminating token of some kind. If the token isn't there, ask for more data then reparse.

Can you help me find a better way to handle that kind of behaviour?

**Comment by lu-zero** [comment]
To me seems least surprising that if an optional is not decidable with the current data it would signal that by default and the whole thing gets forwarded.

You do not want drop an optional because the chunk you have is incomplete generally, IMHO.

**Comment by danielbodart** [comment]
@Geal I don't think we are going to agree, a `field_vchar` might be usable as standalone parser but it's not meant to be. It doesn't matter where you chunk it because you would never use `field_vchar` on it's own. As soon as you put it into the bigger combinators of `header_field` or `headers` or `http_message` chunking just works. 

Following the HTTP RFC by the letter was a pretty great experience showing how well designed the grammar is and I was able to do it by following the grammar exactly. Every test just worked first time except for anything optional, hence why I originally raised this issue.

I fundamentally think that any grammar that ends with an optional element is broken as it's just ambiguous. Excluding those then I think returning incomplete is a trade-off between performance and usability. I prefer usability and having to re-parse a larger chunk as any optional element will always be contained in a larger parser.

Or maybe I'm miss understanding your point. I'm pretty chilled about the whole thing, Feel free to close this. I just have to always remember to do opt!(complete!()). I've actually been meaning to just create a optional! macro anyway.

I'd be interested to see how many projects using nom are doing opt!(complete!()) vs opt!() on it's own.

**Comment by Geal** [comment]
@danielbodart as I mentioned the way your parser is designed, the chunking inside optional components won't affect you, but it might affect others.

I feel there are two points here where we misunderstand each other:
- you talk about trailing optional elements, while I talk about optional elements that can appear anywhere. I agree that trailing optional elements are painful to do if we take optional parsers and incomplete behaviour into account, and there are often better ways to handle them
- "I prefer usability and having to re-parse a larger chunk as any optional element will always be contained in a larger parser": this is where we agree, since the pattern of a parser returning Incomplete to let the calling code reparse with a larger chunk is one of the design decisions in nom. But optional elements can be much larger. Like, in mp4, it's a convention to have the metadata block at the beginning (as it's better for streaming), but the original spec tells you to put it at the end. So you make it optional, and adapt the state machine's behaviour to its presence.

I feel I should t least add more documentation to `opt!` to explain the issue and let people decide what they want. I'd be interested in a survey of how people use that combinator as well.

**Comment by jan-hudec** [comment]
@Geal 
> That's why, if you cannot work on the complete data at once, the optional part should contain a terminating token of some kind. If the token isn't there, ask for more data then reparse.

Just today I wrote a parser where *every* element is `opt!`. And will be writing another one in a couple of days. Because that's what the grammars are. Now in this case, the input is a short string always in memory, so I don't care about incremental processing, but other grammars may exist where the end-of-input is significant. HTTP/0.9 comes to mind as example (the body is terminated by end-of-connection).

> Can you help me find a better way to handle that kind of behaviour?

I think it should be possible to signify the end-of-input condition to the parser. It is not needed often, because most formats do have way to recognise complete input for error checking, but exceptions exist.

> I was not talking about a trailing opt. This could happen right in the middle of your format.

By the way—and I may be misunderstanding things as I didn't find good documentation for this—doesn't the same problem occur for `take_while!`, `digits` and similar?

Say I have:

```rust
#[macro_use]
extern crate nom;

use std::str;
use std::str::FromStr;

named!(
    integer<i32>,
    map_res!(
        map_res!(
            nom::digit,
            str::from_utf8
        ),
        FromStr::from_str
    )
);

fn main() {
    println!("{:?}", integer("123"));
}
```

This prints `Done([], 123)`. However, say my input is actually `12345`, split to `123` and `45`. How will the parser know to return and reparse the whole thing when the first part seemed successful?

It it won't, that would be a bug. If it will, wouldn't the same approach work on the empty inputs?

**Comment by aidanhs** [comment]
Hit this about a week ago. I'm writing a parser for an xml-like syntax and have opted to tokenize first and then parse (after an initial all-in-one approach got a bit hairy). It was a bit surprising to have a `do_parse` on a token of "10%" (where the percentage sign is optional) return `Incomplete` just because the chain of parsers had an `opt` at the end.

I've read the rest of the thread and I can see why this happens, just wanted to give another example of confusion. I probably wouldn't have tripped up if the docs for `opt!` mentioned the issue (perhaps as a note below the example or something).

**Comment by pftbest** [comment]
Hit this issue today. I'm writing a parser for a format where semicolon is optional at the end. So this was parsing correctly: 
```
COMMAND(ARG);
```
but this was giving me `Incomplete`:
```
COMMAND(ARG)
```
If docs for `opt!` had a suggestion to use `opt!(complete!(tag_s!(";")))`, I would have wasted less time.

**Comment by Geal** [comment]
There is now some more documentation on using `opt` with trailing data in a992cb2. This might get easier once #144 advances too.
