### ISSUE TITLE
How can I create a tag!-like parser to check all (MANY) items in a list?

### ISSUE THREAD

**Issue by pashinin** [Geal/nom#415]
What I mean is let's say we have:

```rust
const URI_SCHEMES: [&'static str; 164] = ["aaa", "aaas", "about",
    "acap", "adiumxtra", "afp", "afs", "aim", "apt", "attachment", "aw",
...
```
What macros should I use to check every string in array like:

```rust
named!(pub url_proto,
       alt_complete!(
           tag!("https") |
           tag!("http")  |
           tag!("ftp") |
           ...
       )
);
```
Can I create a parser that checks everything in `URI_SCHEMES`?
Or the only way is to rewrite all of them?

Trying to write it ALL in `alt_complete` gives:
```
error: recursion limit reached while expanding the macro `error_position`
```

**Comment by Geal** [comment]
that would be useful! You're right, using `alt!` or `alt_complete!` for this will not work, so a custom combinator should be written for this.

In the meantime, you have a few options:
- separating the parser on subsets of the list, because:
```rust
named!(pub url_proto,
  alt_complete!(tag!("https") | tag!("http") | tag!("ftp") | tag!("rtp"))
);
```
will do the same as:

```rust
named!(pub http_proto,
  alt_complete!(tag!("https") | tag!("http"))
);
named!(pub other_proto,
  alt_complete!(tag!("ftp") | tag!("rtp"))
);
named!(pub url_proto,
  alt_complete!(http_proto| other_proto)
);
```

You could also write a custom function instead of using the combinators to write it.

In the meantime, I'll get to work on a combinator for this.

**Comment by Geal** [comment]
closing this for now, there's still no combinator for thid, but not much demand. Feel free to reopen if it should really be added
