### ISSUE TITLE
FileProducer should be a thin wrapper?

### ISSUE THREAD

**Issue by crlf0710** [Geal/nom#462]
I think FileProducer should be a thin wrapper around some producer that accepts anything Read + Seek + 'static ?

**Comment by Geal** [comment]
The stream feature will be removed in the next nom version (4.0), since commit 564a93432b52ab99. If someone wants to extract the code and maintain it, feel free to do it, it's in `src/stream.rs`. Otherwise, I would recommend that you check out the (currently in nightly) generators feature, which is much nicer to use. Here's an [example of using nom with generators](https://github.com/geal/generator_nom).
