### ISSUE TITLE
nom4: the trait `std::error::Error` is not implemented for `nom::internal::Err<&[u8]>`

### ISSUE THREAD

**Issue by Keruspe** [Geal/nom#591]
It would be great to have that implemented so that it can be used with `try!` easily

**Comment by Geal** [comment]
from what I see in https://doc.rust-lang.org/std/error/trait.Error.html it would not be terribly useful. The `description` method must return a `&str` :/

**Comment by Keruspe** [comment]
Well, in nom3, it was implemented, so we could bubble up some nom::Error alongside other Errors easily.

**Comment by CAD97** [comment]
What would you think about (optionally?) supporting [`failure`](https://crates.io/crates/failure) for `nom::Err`? `Fail` then offers a `compat` fn for converting to `std::Error` if necessary.

On the other hand, there seems to be support to [forget about `Error::description`](https://github.com/rust-lang/rfcs/pull/2230) and just use the `Display` impl because of the limitations of returning `&'static str`.

Even if you don't want to impl Error or Fail for `nom::Err`, due to whatever reasons, it would be beneficial to provide a compat struct with a `From` impl in order to easily stuff it into a "I don't care; something went wrong" so the option is there.

**Comment by Geal** [comment]
this would be useful for nom 5, and a bit easier to implement

**Comment by whatisaphone** [comment]
Update: The `Error::description` soft-deprecation has landed on stable (quite some time ago actually).

https://doc.rust-lang.org/std/error/trait.Error.html#method.description

>Although using it won’t cause compilation warning, new code should use `Display` instead and new `impl`s can omit it.

The `?` operator is great and it would be nice to be able to use it with `nom`.

**Comment by Stargateur** [comment]
the fact that the error type of nom doesn't implement error is REALLY annoying, you can't use `Box<dyn Error>`. Is there a technical problem to that ?

**Comment by Geal** [comment]
it's now implemented with #1043
