### ISSUE TITLE
Rewriting the README and doc homepage

### ISSUE THREAD

**Issue by Geal** [Geal/nom#674]
Related to #522 

The first place where people get acquainted with nom are usually:

- the [docs homepage](https://docs.rs/nom/4.0.0-alpha2/nom/)
- the [README.md file](https://github.com/Geal/nom/blob/a0ecc9b829c568a07468135a5cf9c8902e4aee1a/README.md) (which is copied on the [crates.io page](https://crates.io/crates/nom))

Those pages are huge and not very user friendly, but I've spent so much time with them thatI need fresh sets of eyes to look at it and criticize, so I can rewrite them properly for the 4.0 release.

Here's what I can see from here:

- README.md:
  - too much emphasis on features, instead of benefits (it should show why use nom less than how to use it)
  - technical details are too early (like compilation features, that should appear in "if you want to do that => use that feature)
  - the usage part looks fine, maybe? But it should be rewritten with nom 4's types (there's still the old `IResult` in there)
  - put more emphasis on combinators like verify (it solves a lot of issues people have), and on pair, terminated, etc (people tend to use do_parse everywhere instead)
  - the list of parsers using nom is nice, but it's missing a lot of suggestions (see #14)
  - add a comparison with benchmarks? I'm not too fond of the idea, but apparently people like to compare parser libraries and come up with benchmarks that make them look good, so maybe I should do it too? Benchmarking nom against C parsers would be nice though

- docs homepage:
  - the "nom parser design" part looks nice to me, it introduces the basic ideas. But maybe it's too early and there should be an example earlier?
  - I tried to write a list of the parsers and combinators by categories, but it's unreadable. Maybe make a table instead? Something with | combinator | input | expected output | ?
  - the calculator example is small but too complex (I'm not too happy about people jumping on `fold_many0`right when they start using nom). Maybe replace it with the [JSON example](https://github.com/Geal/nom/blob/master/tests/json.rs) ?

As a side note, it would be nice to have an `examples/` directory with some nicely written parsers that can be tested right away.

**Comment by sunjay** [comment]
I think [rocket](https://rocket.rs) does a great job in their [README](https://github.com/SergioBenitez/Rocket/blob/master/README.md) and docs. Could be worth considering that when you decide on how to do this.

**Comment by Geal** [comment]
I already see putting an example right at the beginning would be nice

**Comment by focusaurus** [comment]
Here's some notes from someone who recently learned and used nom while also being very new at rust:

- Please make all the early examples complete valid rust programs. When I see `...` I cry because I really don't know what goes in there and I can't build a test program and verify that this stuff actually works. I have 2 personal and 1 overheard anecdote of people using rust docs, getting compiler errors, and having to go to the source code and discover either the docs are simply inconsistent with the actual API published to crates or they need to enable some feature they are unaware of which changes the API.
- I would like to see a much more verbose explanation of what `named!` does. Coming from languages without macros, the fact that this generates a function with the provided name is very unexpected and takes some adjustment.
- Many examples use this type of reference to a slice `&b"abcde"[..]` which I think is unusual to encounter. I'd love to see a paragraph giving this a name and explaining why it's used so much in the nom examples.
- This is not on the home page, but I've still never found a clear explanation of the actual syntax of the `do_parse!` macro. I gleaned what I know using examples, but it seems to me a weird undocumented language and I feel uncomfortable not really knowing the syntax and rules.

**Comment by Geal** [comment]
ok, so, the README should be a bit nicer now. I'll remove the "usage" part from the README and move it to the docs. The idea being that it shows you what's nom and why you want to use it, and the docs tell you how.
I also added a test file for a list of combinators with a short example fo their effect: https://github.com/Geal/nom/blob/master/doc/choosing_a_combinator.md

**Comment by Geal** [comment]
I removed the parser documentation from the readme and moved that to the docs homepage. The list of combinators now lives in https://github.com/Geal/nom/blob/master/doc/choosing_a_combinator.md

**Comment by Geal** [comment]
since I copied stuff around, there's a bit of redundancy in the text, I'll have to fix that
