### ISSUE TITLE
take_until_either! returns error when bytes aren't found

### ISSUE THREAD

**Issue by hwiechers** [Geal/nom#68]
named!(xxx, take_until_either!("!."));

    #[test]
    fn test_take_until_either() {
        assert_eq!(
            xxx(&b"123"[..]),
            nom::IResult::Incomplete(nom::Needed::Unknown)
        );
    }
    //
    //thread 'test_take_until_either' panicked at 'assertion failed: `(left == right)` (left: `Error(Position(14, [49, 50, 51]))`, right: `Incomplete(Unknown)`)'

I'd expect the result of the above to be Incomplete(Unknown) because it's unknown how much more must be read until any of the bytes are found. Is the error result correct? 

Also compare this to take_until...

    named!(xxx2, take_until!("end"));
    
    #[test]
    fn test_take_until() {
        assert_eq!(
            xxx2(&b"123"[..]),
            nom::IResult::Incomplete(nom::Needed::Unknown)
        );
    }
    //
    //thread 'test_take_until' panicked at 'assertion failed: `(left == right)` (left: `Incomplete(Size(4))`, right: `Incomplete(Unknown)`)'

**Comment by Geal** [comment]
In that case, I think `take_until`has a bug, since it has enough characters to decide if there is its terminating byte array. The rationale here would be that you expect to encounter the terminators, otherwise the parser would be successful with partial data.

I have to admit, the whole `take_until*` functions do not really please me. They are confusing, and would be better replaced by explicit code using `many0`, `terminated` and other combinators.
