### ISSUE TITLE
Consider using typed errors

### ISSUE THREAD

**Issue by vberger** [Geal/nom#69]
Currently errors are only a `u32` code, which is not very explicit to interpret.

It would be more user-friendly to use an enum to store error codes, like `std::io::Error` which gives easy access to the `ErrorKind` enum.

It is probably just a matter of integrating this enum https://github.com/Geal/nom/blob/master/src/util.rs#L466-L493 and adding it a `Custom(_)` variant

**Comment by ngrewe** [comment]
I have a  [branch](/ngrewe/nom/tree/typed-errors) that makes the error type in Consumer and ConsumerState generic (and defaults to u32, so it's backwards compatible).I'm not yet convinced that this is the best way to do it (especially since I'm still wondering what to do with producer errors, which nom currently ignores), but it might be a good start.

Cheers,

Niels

**Comment by Geal** [comment]
oh, I did not know there could be default type parameters! This will make things easier for that issue, and other stuff :)

**Comment by Geal** [comment]
I'm currently trying to add this, but apparently, type inference with default type parameters [does not work well](https://users.rust-lang.org/t/default-type-parameter-not-inferred-is-it-a-bug/2706/3).

**Comment by Geal** [comment]
Currently stored in the [typed-errors branch](https://github.com/Geal/nom/tree/typed-errors). Travis shows that the build passes, but it's wrong.

**Comment by Geal** [comment]
Fixed and merged in the 1.0 branch at d47307d

**Comment by Geal** [comment]
Fixed in 1.0
