### ISSUE TITLE
Please document custom error codes

### ISSUE THREAD

**Issue by FauxFaux** [Geal/nom#716]
- nom version: 4.0.0-beta2
- rustc: random recent nightly

I'm working on a [parser](https://github.com/FauxFaux/netzact/blob/a21846e07ca22fbbe5d20111c39aba2105329c95/src/expr/parse.rs#L336), which is successfully using the `verbose-errors` framework, with magic `u32`s everywhere. I'd like to use an enum instead. I cannot work out how to get the code to typecheck.

Is this kind of thing supposed to work, and I've done something dumb?
(I realise that this testcase is probably better handled by casting the enum to a u32, and back again.)

e.g. sample parser, pretty much from the documentation:

```rust
#[macro_use]
extern crate nom;

named!(multi<&[u8], Vnamed!(hw<&str, &str>, add_return_error!(ErrorKind::Custom(2), do_parse!(
    tag!("hello") >>
    world: return_error!(ErrorKind::Custom(3), tag!("world")) >>
    ( world )
)));

named!(root<&str, &str>, add_return_error!(ErrorKind::Custom(1), complete!(hw)));

fn main() {
    match root("hello wellow") {
        Err(nom::Err::Error(e)) | Err(nom::Err::Failure(e)) => {
            for (_loc, kind) in nom::error_to_list(&e) {
                println!("{}", render_kind(kind))
            }
        }
        other => unimplemented!("other return: {:?}", other),
    }
}

fn render_kind(kind: nom::ErrorKind) -> String {
    match kind {
        nom::ErrorKind::Custom(1) => "failed in root".to_string(),
        nom::ErrorKind::Custom(2) => "failed in 'hello world'".to_string(),
        nom::ErrorKind::Custom(3) => "failed in 'world'".to_string(),
        other => format!("unknown failure: {:?}", other),
    }
}
```

This works (almost!) as expected, it prints some useful error feedback.

I was hoping to replace the 1/2/3 magic numbers with an enum, like ([unabbreviated](https://gist.github.com/FauxFaux/9d243acd9548db4323523469cee95de0)):

```rust
// ...
#[derive(Copy, Clone, Debug)]
enum Code {
    World,
    Hw,
    Root,
}

named!(hw<&str, &str, Code>, add_return_error!(ErrorKind::Custom(Code::Hw), do_parse!(
    tag!("hello") >>
    world: return_error!(ErrorKind::Custom(Code::World), tag!("world")) >>
    ( world )
)));

//...

fn render_kind(kind: nom::ErrorKind<Code>) -> String {
    match kind {
        nom::ErrorKind::Custom(Code::Root) => "failed in root".to_string(),
```

... but I get stuck with `u32` being picked up from somewhere:
```
error[E0308]: mismatched types
  --> src/b.rs:12:44
   |
12 |     world: return_error!(ErrorKind::Custom(Code::World), tag!("world")) >>
   |                                            ^^^^^^^^^^^ expected u32, found enum `b::Code`
   |
   = note: expected type `u32`
              found type `b::Code`

error[E0308]: mismatched types
  --> src/b.rs:10:1
   |
10 | / named!(hw<&str, &str, Code>, add_return_error!(ErrorKind::Custom(Code::Hw), do_parse!(
11 | |     tag!("hello") >>
12 | |     world: return_error!(ErrorKind::Custom(Code::World), tag!("world")) >>
13 | |     ( world )
14 | | )));
   | |____^ expected enum `b::Code`, found u32
   |
   = note: expected type `std::vec::Vec<(&str, nom::ErrorKind<b::Code>)>`
              found type `std::vec::Vec<(&str, nom::ErrorKind)>`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

...
```

`cparser` uses this `into_nom` pattern, and I don't see how it would help. It doesn't help me. ([unabbreviated](https://gist.github.com/FauxFaux/9d243acd9548db4323523469cee95de0#file-nom-testcase-c-rs)):

```rust
// ...
impl Code {
    fn into_nom(self) -> nom::ErrorKind<Code> {
        nom::ErrorKind::Custom(self)
    }
}

named!(hw<&str, &str, Code>, add_return_error!(Code::Hw.into_nom(), do_parse!(
    tag!("hello") >>
    world: return_error!(Code::World.into_nom(), tag!("world")) >>
    ( world )
)));
// ...
```

```
error[E0308]: mismatched types
  --> src/c.rs:18:26
   |
18 |     world: return_error!(Code::World.into_nom(), tag!("world")) >>
   |                          ^^^^^^^^^^^^^^^^^^^^^^ expected u32, found enum `c::Code`
   |
   = note: expected type `nom::ErrorKind<u32>`
              found type `nom::ErrorKind<c::Code>`

error[E0308]: mismatched types
  --> src/c.rs:16:1
   |
16 | / named!(hw<&str, &str, Code>, add_return_error!(Code::Hw.into_nom(), do_parse!(
17 | |     tag!("hello") >>
18 | |     world: return_error!(Code::World.into_nom(), tag!("world")) >>
19 | |     ( world )
20 | | )));
   | |____^ expected enum `c::Code`, found u32
   |
   = note: expected type `std::vec::Vec<(&str, nom::ErrorKind<c::Code>)>`
              found type `std::vec::Vec<(&str, nom::ErrorKind)>`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

It's still picking up the `u32` from somewhere, presumably a child parser?

**Comment by Geal** [comment]
Hello, it's picking up the `u32` from the previous `tag!("hello")`. To avoid type inference errors due to custom error codes, all of the basic parsers (`tag!`, `take!`, `digit`, etc) have a `u32` as custom error code. You could wrap the parser like this `fix_error!(Code, tag!("hello"))` to convert the error codes, but I have not been able to convert the eror codes implicitely yet.

**Comment by kyrias** [comment]
Would be good if this was in the docs for all the macros that do this, just spent quite some time trying to figure out why it wouldn't accept my custom error type, hah.

**Comment by bwo** [comment]
Failure to mention this in the documentation is a huge shortcoming, IMO, and the pain involved in using non-`u32` types in any nontrivial parser (especially since, as was observed in a previous, now closed issue, mostly people will write parsers for the correct grammar, and then add in error handling later) makes the theoretical ability to choose a custom type not super compelling.

I would much rather be forced to write `tag!(E, "tag")` with E being the error type _explicitly_ than have `tag!` internally always choose `u32`, requiring me to write a (likely boilerplate) `From<u32>` for my type. Indeed, just as `named!` passes down its input parameter, it could presumably pass down the type parameter as well.

**Comment by bwo** [comment]
Failure to mention this in the documentation is a huge shortcoming, IMO, and the pain involved in using non-`u32` types in any nontrivial parser (especially since, as was observed in a previous, now closed issue, mostly people will write parsers for the correct grammar, and then add in error handling later) makes the theoretical ability to choose a custom type not super compelling.

I would much rather be forced to write `tag!(E, "tag")` with E being the error type _explicitly_ than have `tag!` internally always choose `u32`, requiring me to write a (likely boilerplate) `From<u32>` for my type. Indeed, just as `named!` passes down its input parameter, it could presumably pass down the type parameter as well. (I realize this would likely be a lot of work to implement.)

**Comment by Geal** [comment]
@bwo that's a good idea, I'll try that. I'm still hoping there will be type inference fixes in recent rust versions, that would relax nom's requirements

**Comment by Geal** [comment]
the `verbose-errors` feature was removed in nom 5, and custom errors have now disappeared. Instead, we can specify the error type more easily through a generic parameter. See https://github.com/Geal/nom/blob/master/examples/json.rs for an example of flexible error management
