### ISSUE TITLE
escaped_transform infinit loops over control variable

### ISSUE THREAD

**Issue by candronikos** [Geal/nom#787]
Hi,

The issue I'm having is that the test hangs forever whenever I try to exclude the control character `\` from `is_unicode_str_char`. And when I leave it out, the output is incorrect.

## System info

- Rust version : rustc 1.26.0 (a77568041 2018-05-07)
- nom version : 4.0.0
- nom compilation features used: verbose-errors

## Test case

```rust
#[macro_use]
extern crate nom;
use nom::types::CompleteStr;
use nom::{Needed};
pub type Input<'a> = CompleteStr<'a>;

fn is_unicode_str_char(c: char) -> bool {
    print!("\n{:?}:{:?}\n",c,c>=(0x20 as char) && c!='\\');
    c>=(0x20 as char) && c!='\\'
}

named!(str_chars<Input,String>,
    escaped_transform!(
        take_while!( is_unicode_str_char ), '\\', alt!(
            //tag!("\\") => { |x| x } |
            //tag!("\"") => { |x| x } |
            tag!("\\") => { |_| CompleteStr("\\") } |
            tag!("\"") => { |_| CompleteStr("\"") } |
            tag!("n") => { |_| CompleteStr("\n") }
        )
    )
);

fn main() {
  assert_eq!(str_chars(CompleteStr("\\nab\\na")), Ok((CompleteStr(""), "\"ab\"a".to_owned())));
}
```

## Output
```
'\\':false
'\\':false
'\\':false
'\\':false
'\\':false
'\\':false
'\\':false

// Forever and ever :)
```

**Comment by siler** [comment]
The take_while macro can return an empty slice if the first character of the string does not match your predicate. When take_while returns an empty slice, escaped_transform does not understand that there is a transform that needs to take place (it receives an empty slice instead of an Error() which indicates that the current character is not 'normal'). To fix this, use take_while1 instead, which provides an error when it is unable to retrieve a 'normal' character.

**Comment by Geal** [comment]
yes, replacing with `take_while1` should work
