### ISSUE TITLE
Default to host endianness

### ISSUE THREAD

**Issue by beatgammit** [Geal/nom#823]
It seems the Rust standard library makes dealing with the host's endianness a pain while making explicit endianness easier. I get the reason behind this, but some formats don't have an explicit endianness.

I'm working on a toy parser for Lua bytecode, which includes an endianness check, and luac apparently uses the host's endianness for its data format. I can assume little endian for now (that's my dev machine) and potentially have the endianness passed in (e.g. by testing the host's endianness), but it would be nice to just ignore explicit endianness for this particular format.

I would like i32 and friends to use the host's endianness if it's not explicitly passed in. This seems fair to me, and defaulting to little endian is a bit surprising IMO. Granted, little endian is the most common (x86), it's not universal, and big endian seems more common for formats anyway (network byte order).

**Comment by demurgos** [comment]
I'd prefer the default to not depend on the host machine (no hidden host-dependent change in behavior). I'm not even sure if having a default is really needed. I thing it's better to require people to use `le_u32` explicitly rather than relying on the default of `u32`. It requires people to actually consider endianness issues before writing their parser.

Regarding host endianness, I agree that it would be nice to have since there are use cases depending on it. What about adding `Endianness::Host` and `host_u32` (etc.)?

Until it's supported, you could write your own `host_*` functions for your project (with detection of the host endianness).

**Comment by demurgos** [comment]
[`byteorder` has `NativeEndian`](https://github.com/BurntSushi/byteorder/blob/820e49cce636c115a1edca905f58986a54bb2116/src/lib.rs#L1793-L1813)

:bike::house: It may be good for consistency across the ecosystem to use `Native` instead of `Host`. I initially went with "host" because it's shorter, but consistency may be more important.

You could write a macro to generate all the aliases based on the endianness (using `#[cfg(target_endian = ...)]`)

**Comment by Geal** [comment]
i'd be open for a PR adding native endian combinators and parsers

**Comment by Geal** [comment]
the new number parsers with configurable endianness now have a native option: 1baaa7c
