### ISSUE TITLE
alpha takes more than the documented characters

### ISSUE THREAD

**Issue by sunjay** [Geal/nom#828]
## Prerequisites

Rust version:

```
$ rustc --version --verbose
rustc 1.28.0 (9634041f0 2018-07-30)
binary: rustc
commit-hash: 9634041f0e8c0f3191d2867311276f19d0a42564
commit-date: 2018-07-30
host: x86_64-unknown-linux-gnu
release: 1.28.0
LLVM version: 6.0
```

nom version: 4.0.0
nom features: verbose-errors

## Test case

```rust
extern crate nom;

use nom::alpha;

fn main() {
    // 0x03b1 = greek letter α
    assert!(alpha("\u{03b1} ").is_err());
}
```

This assertion will fail. The documentation for `alpha` says:

> Recognizes one or more lowercase and uppercase alphabetic characters: a-zA-Z

However, the implementation of `AsChar` for `char` uses [`is_alphabetic`](https://doc.rust-lang.org/std/primitive.char.html#method.is_alphabetic) which will accept way more than that including the greek letter α as shown above. This function is documented as:

> Returns true if this char is an alphabetic code point, and false if not.

In my case, this is not an issue, so I would be okay with just updating the documentation to point out that `alpha` will accept any alphabetic **code point** (not just a-zA-Z).

That's probably a breaking change though. Fixing this might also be a breaking change though, so maybe this is something for nom 5.0? :)

**Comment by kaj** [comment]
The problem here is that the behaviour differs between byte parsers (taking `&[u8]` input) and string parsers (taking `&str` input).  The behaviour @sunjay describes is what happens for string parsers, while the documented behaviour is what happens for byte parsers.

I would prefer if byte parsers behaved like string parsers in this case, but if that is a breaking change, maybe the difference can be pointed out in the documentation?  If there also is a simple way to recognize a valid utf-8 code point in a byte parser, a link to that would be helpful as well.

The following test will succeed:

```rust
extern crate nom;

use nom::alpha;

#[test]
fn from_str() {
    // 0x03b1 = greek letter α
    assert_eq!(alpha("\u{03b1} "), Ok((" ", "\u{03b1}")));
}

#[test]
fn from_bytes() {
    // 0x03b1 = greek letter α
    assert!(alpha("\u{03b1} ".as_bytes()).is_err());
}
```

I would prefer if the `from_bytes` test failed and `from_bytes2`, which is currently failing, worked instead.

```rust
#[test] // This is currently failing
fn from_bytes2() {
    // 0x03b1 = greek letter α
    assert_eq!(
        alpha("\u{03b1} ".as_bytes()),
        Ok((&b" "[..], "\u{03b1}".as_bytes()))
    );
}
```

For what it's worth, here's the parser I hope to use to get a single utf8 code point (i.e. a rust `char`) from a byte parser.  It doesn't feel very efficient, but I think it is at least working:

```rust
named!(
    take_char<char>,
    map_opt!(
        alt!(take_str!(1) | take_str!(2) | take_str!(3) | take_str!(4)),
        |s: &str| s.chars().next()
    )
);
```

**Comment by sunjay** [comment]
> I would prefer if byte parsers behaved like string parsers in this case

My (limited) understanding of this is that utf8 code points can be multiple bytes, so we can't implement things the same way for a `u8`. We would have to convert `&[u8]` to a `&str` inside of `alpha` which is expensive and can potentially fail if the bytes aren't valid UTF-8.

That's why the behaviour is implemented as it is today. Some feasible approaches would be to either:

1. change the documentation to mention the difference between types (maybe even mention the trait involved)
2. change the implementation for `&str` to use ASCII operations (not necessarily desirable--and a breaking change)

**Comment by Geal** [comment]
oh, that's an annoying bug, and you're right, that would probably be a breaking change. I don't know yet what I'll do, but I'm keeping that issue around for the next version

**Comment by sunjay** [comment]
@geal would it be good to update the documentation to warn people about this behavior?

**Comment by sunjay** [comment]
Thank you! 😁

**Comment by Geal** [comment]
breaking change in nom 5: they will recognize ASCII by default
24ef7f1
