### ISSUE TITLE
Potential bug in `tag!` and `tag_no_case!` (mismatched type with custom error type)

### ISSUE THREAD

**Issue by Centril** [Geal/nom#832]
## Prerequisites

- Rust version : rustc 1.30.0-nightly (aaa170beb 2018-08-31)
- nom version : 4.0.0
- nom compilation features used: default features.

## Test case

```rust
#[macro_use] extern crate nom;

struct Error;

named!(merge<&str, &str, Error>, tag!("merge"));
```

Expected: For this to compile (`cargo check`)

Actual:

```rust
error[E0308]: mismatched types
  --> src\command.rs:63:1
   |
63 | named!(merge<&str, &str, Error>, tag!("merge"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `command::Error`, found u32
   |
   = note: expected type `std::result::Result<(&str, &str), nom::Err<&str, command::Error>>`
              found type `std::result::Result<(&str, &str), nom::Err<&str, u32>>`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

This happens because of:
+ https://docs.rs/nom/4.0.0/src/nom/bytes.rs.html#36
+ https://docs.rs/nom/4.0.0/src/nom/bytes.rs.html#77

The error type is constrained to `u32`.

If this is indeed a bug (might be expected behavior?) then solving this might cause inference problems.
I'll work around this locally for now.

**Comment by Geal** [comment]
hello,
the error type has been constrained to `u32` because there were a lot more type inference problems before. It was possible to define a parser entirely without specifying the error type, and the code could never compile.

The usual workaround for now is to use [fix_error](https://docs.rs/nom/4.0.0/nom/macro.fix_error.html). This combinator will convert to your custom error code, as long as it implements `From<u32>`.
