### ISSUE TITLE
Unintuitive behavior of `separated_list`

### ISSUE THREAD

**Issue by loewenheim** [Geal/nom#834]
The `separated_list`combinator behaves differently from how I would expect it to when used in combination with `opt`. Example:

```rust
use nom::*;
use nom::types::CompleteStr;

named! {
    x<CompleteStr, char>,
    value!('x', tag!("x"))
}

named! {
    x_list<CompleteStr, Vec<Option<char>>>,
    separated_list!(tag!(","), opt!(x))
}

fn main() {
    println!("{:?}", x(CompleteStr("x")).unwrap());
    //(CompleteStr(""), 'x')
    println!("{:?}", x_list(CompleteStr("x,x,x")).unwrap());
    //(CompleteStr(""), [Some('x'), Some('x'), Some('x')])
    println!("{:?}", x_list(CompleteStr("x,,x")).unwrap());
    //(CompleteStr(",,x"), [Some('x')])
}
```
I would expect the result `(CompleteStr(""), [Some('x'), None, Some('x')])`in the last case. Am I misunderstanding something?

I compiled this with `nom 4.0.0` and `rustc 1.30.0-nightly`.

**Comment by Geal** [comment]
parsers like `separated_list` or `many0` will stop if one of their child parsers return true without consuming the whole input, to avoid infinite loops. Maybe that rule could be relaxed for `separated_list`, like this:
- the element parser could succeed without consuming any input
- the separator parser would be kept strict

But I'm wondering how we should handle the case of the empty list. Should it return a list with one element, or an empty list, or an error?

**Comment by AntonyBlakey** [comment]
I think the opposite should be true - I have many instances like this:

`separated_list!(optional_whitespace, high_level_element)`

that fail if the `high_level_element` consumes trailing whitespace. Maybe it should succeed if *either* of the child parsers consumes input? That would be the correct response to avoid an infinite loop, but would preserve both intuitive behaviours.

**Comment by Geal** [comment]
it would make no sense for separated list to succeed if the separator succeeds but not the other parser.
If you have optional whitespace it should not be treated as separator. You could write it as `many0!(preceded!(optional_whitespace, high_level_element))`.
Note that if you want a custom behaviour, it's also possible to make your own combinator, it's easy to extend nom :)

**Comment by AntonyBlakey** [comment]
It's not about success/failure of the child parsers, but about the guard against an infinite loop being whether they *both* must consume input on each iteration.

I've done both of the things you suggest to deal with this, but I think that productions that can succeed without consuming input in either the separator or element positions are valid use cases. In any case, I think the current behaviour of those library-supplied combinators is not intuitive, and is not required to avoid the infinite loop.

**Comment by Geal** [comment]
I should probably make things a bit more explicit: the infinite loop guard is not meant as a feature to rely on, but a fix for mistakes when writing parsers. It is not something that should be intuitive, it's something that should be ignored.
The question of whether this test should be present or not is interesting, and personally I'd like to remove it, but then I'd have to deal with support requests for parser bugs that would have been caught by it.

**Comment by AntonyBlakey** [comment]
I understand the point about the infinite loop test not being part of the behaviour of the combinator - in fact, that's my point. At the moment, that test has a more significant side-effect on the combinator semantics than it needs to. An infinite loop can only occur if the input at the end of the loop (in the implementation) is unchanged from the beginning of the loop, which is what the test should be IMO. In that case, either of the child parsers could consume no input, but not both.

That would have a lot less impact on the behaviour of the combinator. And it's *that* behaviour that I think is currently somewhat unintuitive.

Actually, in the presence of stateful combinators, that might conditionally consume input on some hidden state, even that test could be intrusive, but I think a comment in the documentation saying that at least one of the children must consume input would be sufficient.

I agree that catching an infinite loop is really useful when building parsers, and not just because it cuts down your support load :)
