### ISSUE TITLE
`tuple_parser` and `error_position` not found in scope

### ISSUE THREAD

**Issue by rbalicki2** [Geal/nom#850]
## Prerequisites

Here are a few things you should provide to help me understand the issue:

- Rust version : rustc 1.32.0-nightly (6b9b97bd9 2018-11-15)
- nom version : 4.1.1
- nom compilation features used: none

## Test case

If you are using Rust 2018 edition (or otherwise import nom without macro_use), you can still import the `tuple!` etc parsers directly. However, they do not work, because they reference other macros.

I've noticed it with `tuple_parser` and `error_position`, although presumably it happens with others.

It is obviously not a problem for me to import these separately, however, it would be more elegant if I could import them through a prelude or if the macros were referenced with their full 2018 path. (That might break pre-2018 code, though, so... /shrug)

Thanks for the great library!

**Comment by Zarenor** [comment]
I feel a need to clarify a little bit.
Changing to edition 2018 should not break anything (whether in edition 2018 or not), because that syntax processing is applied on a crate-by-crate basis. However, as with all compiler and language features, it does bump the minimum rustc version to one which supports the edition (1.31 will be the first such stable version, to be released in early December).

It's important to be clear about this, though, because these kinds of compatibility guarantees are important to the rust team. If something isn't importing properly, it may be a compiler bug to look at.

With all that said, I'm not entirely clear on what exact `use` statements you're writing that don't work, and what `use` statements you're writing that do. 
The bulk of the module system changes are *not* Rust 2018 features. They were stabilized for the entire ecosystem with Rust 1.30, including the changes to whether you need `::` before crate names and removing the need for `#[macro_use]` in most cases.

If you could perhaps show us (rather than describe to us) the code which does and does not work, that would be really helpful in deciding what we can do to solve the issue.

**Comment by Geal** [comment]
the issue here is that some nom macros internally use other macros. With previous Rust crates, all macros are brought into scope, so it's fine, but with Rust 2018, they are imported like functions, so it's not transparent anymore.
I'm planning to do a new major version of nom to migrate to 2018 edition, that will fix the issue.

**Comment by xfix** [comment]
I wonder, doesn't e3fa8e71279738e03ac057e8e426eed416e00b2e fix that?

**Comment by Geal** [comment]
this should be fixed in nom 4.2.2
