### ISSUE TITLE
Lack of searchable up-to-date documentation

### ISSUE THREAD

**Issue by spease** [Geal/nom#874]
One thing I've noticed nom (and a lot of other parsers incidentally) seems to be weak on is documentation and examples. In nom's case, a lot of the searchable stuff that comes up is outdated. In addition, the rust docs also tend to not have any documentation at all for a lot of the combinators (if this isn't captured either, it should probably be captured in a separate ticket).

TBH, once I find an example or a description, most of the combinators tend to be pretty simple and easy to use. However when there are gotchas (eg CompleteStr, or having to do `terminated!(..., eof!())` instead of `complete!(...)`) it tends to burn a *lot* of time to figure out from miscellaneous questions and answers online to figure out what the "right" way to do things is.

Looking at other libraries isn't a good solution, since they tend to be a lot more complex, so you end up having to click through and find the parser and then sort through everything going on... and then you can also run into out-of-date issues. This also means that work is repeated for everybody who has to use the library.

I suspect this kind of thing silently defers people from using the library, although by definition it'd be hard to prove that's the case.

**Comment by Geal** [comment]
so, a few things here:
- which parts of the documentation are not up to date? Code examples are compiled as parts of the tests, so they should match the current version
- did you read the tutorials in https://github.com/Geal/nom/tree/master/doc ?
- `CompleteStr` was an attempt to fix some usability issues, especially with ends of files, but it will be dropped in nom 5 in favor of a better solution
- how is the documentation not searchable? What is it missing there?

**Comment by spease** [comment]
1) 
Supposing I do a search for "rust nom" in Google to try and get started:
![image](https://user-images.githubusercontent.com/2825204/54078498-dc8bb780-427d-11e9-9e41-bf4ce8691257.png)

The first and second link are OK, they're up to date and provide links to 'getting started' or 'reference' resources. However if I try to search the documentation like I would a typical Rust library, it's kind of hit and miss. This seems to be getting better with time.

The third, fourth, and fifth links are woefully out-of-date.

This is more of an SEO complaint than a documentation complaint, however I think doing more to make the Rust documentation a first-class citizen will help. Having examples for each combinator, etc. One thing that also isn't clear is what 'type' each combinator is, eg a conditional vs consuming input.

2)
As far as reading the documentation, no, not up-front in a waterfall style. A lot of times when I reach for a tool, I have another task that I'm in the middle of. I don't have the time to drop everything and spend hours learning how to use that library. I probably want to use the "easy" interface.

Looking through the nom docs, I've definitely read parts of them before, mostly the choosing a combinator one, which is what I'm thinking of when I mention the "combinator" reference. I believe I've also read through "error management" as well, particularly when I was debugging combinators. Reading through "upgrading_to_nom" when my parsers broke after an upgrade and I needed to upgrade to CompleteStr, however it took me awhile to find the document (I believe I ended up just temporarily commenting out that code for awhile until I had to fix it).

In general I have no interest in wading through pages of text before I have any kind of mental model to put said text in. A lot of times, it's frustrating or a waste of time. Either I'm fighting to ignore most of the information to try to preserve my working memory for the current task, or I end up purging all my working memory of the actual task I'm trying to do and then forgetting virtually everything I read. Because nothing is meaningful until I get to the point where a mental model is provided that allows me to prioritize information.

For instance, the FAQ (the first item in docs) starts out with "Using nightly to get better error messages" or "The compiler indicates error: expected an item keyword then points to the function's return type in named!:" or "
nom 1.0 does not compile on Rust older than 1.4". If I did see the FAQ the first time I started using nom, I would have just skipped over these - I've always preferred to use stable unless I have to switch to nightly for some tool, even now I'm not sure what the second one means, and the third one is irrelevant.

When learning something like this, I would want to see what the setup process is like for a minimal example. Then get some basic explanation for what's happening. Then understand what the 'types' or categories are (test vs consumer vs debug vs function-makers etc...). Then get some basic tips on debugging. Then hand off to the advanced categories at the point that I understand the model well enough to know what it is that I need to help myself (eg I want to look for a digit with a sign, so I must be looking something that consumes using a tester).

I think what would also help here would be to group the combinators in modules by what they are for the sake of documentation, and then put them all into the prelude for the sake of ease of inclusion (now that we are in Rust 2018 era and can `use` macros).

Or, alternatively, do a zero-cost abstraction thing combinators are more strongly-typed. Although IIRC I run into more ambiguous macro issues than type issues, but then, I'm usually trying to stick to stable for projects and so only drop into nightly if I'm stuck enough to justify rebuilding everything. So the errors I'm getting may be much more informative in nightly. (I don't remember exactly what they are, just that they usually translate into "forgot/added a parentheses" or "accidentally left a comma" or "Combinator needs value mapped to a &str first" or "needs a `char!`").

3) 👍

4) I sort of answered this with (1), but I'm talking more about the guides that come up if you run into a problem and try to google it. I have this same problem with other libraries too, particularly the Rust manual - I keep getting brought to what looks like the right page, then invariably it tells me that there's a newer version of the book available and drops me to the front page rather than the section I'm looking for.

Apart from SEO and using server-side hints to steer Google towards up-to-date versions, or writing new guides, I'm not sure what the solution is here.

**Comment by sinesc** [comment]
Regarding outdated documentation, I suspect the error_management.md is a case of this. E.g. this ["list of basic types in Nom"](https://github.com/Geal/nom/blob/master/doc/error_management.md#error-reporting):  I'm not sure what I'm seeing here. Err and IResult are listed twice without any explanation. I suspect it's different Nom versions or maybe related to the verbose error config. Might also be a copy&paste error.

Next paragraph is ["adding an error"](https://github.com/Geal/nom/blob/master/doc/error_management.md#adding-an-error).  
The examples don't compile due to missing imports. It is unclear where to find those. Searching the docs  for Error yields an enum variant, NodePosition yields nothing at all.

Same for ["early returns"](https://github.com/Geal/nom/blob/master/doc/error_management.md#early-returns). Additionally when dumping res_a and res_b they are identical, indicating that the early return doesn't actually work or is overwritten by the outer error, which is the problem I'm trying to figure out in my project right now.

I've picked error reporting as an example because that's what I'm currently looking into, but similar remarks could be made about many areas of the documentation, e.g. whitespace handling (what does the `sep!` example even do and why does it differ from the one in `nom::whitespace`?). 

I don't mean this to sound discouraging or unappreciative because Nom is pretty great once you know how to do XYZ with it, but in retrospect I'm certain it would have been much faster and significantly less frustrating for me to manually implement the parsing stage (for a toy language with Rust syntax) than to figure out how to do said XYZ in Nom. But I have some experience doing that, so maybe that's not a fair comparison.

Given that you are working on Nom 5, documenting Nom 4 is probably not the most useful thing to do either for anybody, so I'm not sure how to give some constructive criticism here. Concise how-to-do-XYZ examples for Nom 5 would be fantastic, solid error handling documentation would really help a lot, so would simplifying it, but I think that's what you're planning for with the removal of verbose errors. Cross-referencing macros would save some time, e.g. put a "See also: `preceeded!`" in the documentation for `terminated!`.

**Comment by Geal** [comment]
The way I'm building nom 5, there will be a complete documentation rewrite (or at least, I'll manually go through all docs and examples and make sure they're up to date). The error management doc especially will be rewritten, since I've found a better way to implement errors in nom 5: #887

**Comment by Geal** [comment]
the documentation rewrite is done
