### ISSUE TITLE
port byte level parsers to the new design

### ISSUE THREAD

**Issue by Geal** [Geal/nom#893]
The code is in `src/bytes/macros.rs`
Missing ones:
- `escaped`
- `escaped_transform`
- `take_until_and_consume`
- `take_until_and_consume1`
- `take_until1`
- `take_until_either_and_consume`
- `take_until_either_and_consume1`
- `take_until_either`
- `take_until_either1`

This might be a good time to remove a few of those, especially the `take_until_*`

**Comment by Waelwindows** [comment]
I'm thinking of taking over this task, and so I am currently working on porting over the macros  to the new nom 5.0 system.

However, I have a question about the macro definitions. Currently the `take_until` macro is defined as 
```rust
($i:expr, $substr:expr) => ({
  let res: $crate::IResult<_,_,_> = $crate::take_until($substr)($i);
  res
});
```
However, I don't see any reason why it shouldn't be re-written as 
```rust
($i:expr, $substr:expr) => ($crate::take_until($substr)($i));
```
Especially since it's eliding the the type parameters, and the function itself provides the type, thus no type hints are required in the first place.  This would affect other macro definitions, but is out of scope for the current task

**Comment by Geal** [comment]
yes, it can be rewritten that way, this is leftover from code before the error management rewrite. For combinators like `take_until`, I had to write `let res: $crate::IResult<_,_,u32> = $crate::take_until($substr)($i);` because rustc was not able to infer the error type, but then I had hacks in place with the `nom::Convert` trait and the `fix_error` macros for cases where people wanted something else than `u32` as error type.
With the new error system, none of that is needed 😎

**Comment by NamsooCho** [comment]
@Waelwindows do you still hold this issue? If you release it, I would take this issue.

**Comment by Geal** [comment]
@NamsooCho I'm currently working on the last remaining byte level combinators, those for escaping, and they're a bit tricky to do. Meanwhile I could really use some help on documentation and examples (cf #914 and #915)

**Comment by Waelwindows** [comment]
Sorry for not replying, but I have been working on it. I managed to port over all parsers except `escaped` and `escaped_transform`. For `escaped` I managed to implement the function but the Input trait bounds make it difficult to implement the macro. As such i haven't been able to work on `escaped_transform`

**Comment by Geal** [comment]
`escaped` and `escaped_transform` migrations are now done with f48af68
