### ISSUE TITLE
3.0 -> 4.0 breaking changes: eof handling

### ISSUE THREAD

**Issue by Dushistov** [Geal/nom#909]
Hello, and thank you for submitting an issue to nom!
## Prerequisites

- Rust version : `rustc -V`
`rustc 1.33.0 (2aa4c46cf 2019-02-28)`
- nom version :
`v4.2.3` and `v3.2.1`
- nom compilation features used:
default ones

## Test case

Example test case bellow,
it works fine with `v3.2.1`, but failed on `v4.2.3` with
`Incomplete(Size(1))`

```Rust
use nom::*;
use std::str;

named!(
    parse_gsv_sat_info<(u32, Option<i32>)>,
    map_res!(
        do_parse!(
            prn: map_res!(digit, parse_num::<u32>)
                >> char!(',')
                >> signal_noise: opt!(map_res!(complete!(digit), parse_num::<i32>))
                >> alt!(eof!() | tag!(","))
                >> (prn, signal_noise)
        ),
        |x| -> std::result::Result<(u32, Option<i32>), &'static str> { Ok(x) }
    )
);

fn parse_num<I: std::str::FromStr>(data: &[u8]) -> std::result::Result<I, &'static str> {
    str::parse::<I>(unsafe { str::from_utf8_unchecked(data) }).map_err(|_| "parse of number failed")
}

fn main() {
    assert_eq!((14, None), parse_gsv_sat_info(b"14,").unwrap().1);
}
```

**Comment by Geal** [comment]
hello,
those breaking changes were documented here: https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#dealing-with-incomplete-usage

Although, maybe hold off on using `CompleteByteSlice` to solve this issue, since they will be removed in nom 5. They are awkward to use, and do not solve all issues, while the new design makes most parsers simpler. nom 5 will probably be released in a month or two
