### ISSUE TITLE
Regex parsers to be ported from macros to functions

### ISSUE THREAD

**Issue by cpdean** [Geal/nom#978]
Per the 5.0 release, one of the [goals was to port macros over to functions](https://github.com/Geal/nom/issues/878).

The regex parsers have not yet gotten ported. 

I am sorry that I do not have a good test case for this, but the current test suite for regex-based parsers [still use the macro versions](https://github.com/Geal/nom/blob/5.0.0/src/regexp.rs#L663-L685):

```
  #[cfg(feature = "alloc")]
  #[test]
  fn re_capture() {
    named!(rm< &str,Vec<&str> >, re_capture!(r"([[:alpha:]]+)\s+((\d+).(\d+).(\d+))"));
    assert_eq!(
      rm("blah nom 0.3.11pouet"),
      Ok(("pouet", vec!["nom 0.3.11", "nom", "0.3.11", "0", "3", "11"]))
    );
    assert_eq!(
      rm("blah"),
      Err(Err::Error(error_position!(
        &"blah"[..],
        ErrorKind::RegexpCapture
      )))
    );
    assert_eq!(
      rm("hello nom 0.3.11 world regex 0.1.41"),
      Ok((
        " world regex 0.1.41",
        vec!["nom 0.3.11", "nom", "0.3.11", "0", "3", "11"]
      ))
    );
  }
```

**Comment by loewenheim** [comment]
I’ve started working on this. Am I correct in assuming that the various `_static` macros do not make sense as functions? A possibility for fixing this would be to provide various functions that take an already compiled regex as an argument instead of a string. One could then always use `lazy_static` manually to provide the regex at compile time.

**Comment by Lucretiel** [comment]
Imo there shouldn't be any need to use lazy_static in the function-based versions, because even if you take a pattern string instead of a `Regex`, you can still do:

```rust
fn regex_parse(pattern: &str) -> impl Fn(&str) -> IResult<...> {
    let regex = Regex::new(pattern).unwrap();
    move |input| { ... }
}
```

However, I'd argue against a form like this; just accept a `Regex` or `&Regex` object and let the caller be responsible for its origin.
